import 'package:flutter/material.dart';
import 'package:flutter_countries/countryModel.dart';
import 'package:flutter_countries/pages/countries.dart';
import 'package:flutter_countries/pages/quizz.dart';
import 'package:auto_size_text/auto_size_text.dart';

class Home extends StatefulWidget {
  final List<C> dataFr = [
    C(26, 'Afghanistan', 'Proche-Orient', 'Kaboul'),
    C(36, 'Afrique du Sud', 'Afrique', 'Pretoria'),
    C(105, 'Albanie', 'Europe', 'Tirana'),
    C(20, 'Algérie', 'Afrique', 'Alger'),
    C(21, 'Allemagne', 'Europe', 'Berlin'),
    C(183, 'Andorre', 'Europe', 'Andorre-la-Vieille'),
    C(35, 'Angola', 'Afrique', 'Luanda'),
    C(184, 'Antigua-et-Barbuda', 'Océanie', 'Saint Johns'),
    C(19, 'Arabie saoudite', 'Proche-Orient', 'Riyad'),
    C(29, 'Argentine', 'Amérique du Sud', 'Buenos Aires'),
    C(76, 'Arménie', 'Proche-Orient', 'Erevan'),
    C(138, 'Australie', 'Océanie', 'Canberra'),
    C(46, 'Autriche', 'Europe', 'Vienne'),
    C(39, 'Azerbaïdjan', 'Proche-Orient', 'Bakou'),
    C(149, 'Bahamas', 'Océanie', 'Nassau'),
    C(155, 'Bahreïn', 'Proche-Orient', 'Manama'),
    C(7, 'Bangladesh', 'Asie', 'Dacca'),
    C(161, 'Barbade', 'Océanie', 'Bridgetown'),
    C(74, 'Belgique', 'Europe', 'Bruxelles'),
    C(186, 'Belize', 'Amérique centrale', 'Belmopan'),
    C(151, 'Bénin', 'Afrique', 'Porto-Novo'),
    C(163, 'Bhoutan', 'Asie', 'Thimphou'),
    C(50, 'Biélorussie', 'Europe', 'Minsk'),
    C(87, 'Birmanie (Myanmar)', 'Asie', 'Naypyidaw'),
    C(92, 'Bolivie', 'Amérique du Sud', 'La Paz'),
    C(135, 'Bosnie-Herzégovine', 'Europe', 'Sarajevo'),
    C(150, 'Botswana', 'Afrique', 'Gaborone'),
    C(33, 'Brésil', 'Amérique du Sud', 'Brasilia'),
    C(181, 'Brunei', 'Asie', 'Bandar Seri Begawan'),
    C(134, 'Bulgarie', 'Europe', 'Sofia'),
    C(81, 'Burkina Faso', 'Afrique', 'Ouagadougou'),
    C(73, 'Burundi', 'Afrique', 'Gitega'),
    C(42, 'Cambodge', 'Asie', 'Phnom Penh'),
    C(54, 'Cameroun', 'Afrique', 'Yaoundé'),
    C(91, 'Canada', 'Amérique du Nord', 'Ottawa'),
    C(158, 'Cap-Vert', 'Océanie', 'Praia'),
    C(110, 'République centrafricaine', 'Afrique', 'Bangui'),
    C(18, 'Chili', 'Amérique du Sud', 'Santiago'),
    C(1, 'Chine', 'Asie', 'Pékin'),
    C(144, 'Chypre', 'Proche-Orient', 'Nicosie'),
    C(13, 'Colombie', 'Amérique du Sud', 'Bogota'),
    C(169, 'Comores', 'Océanie', 'Moroni'),
    C(75, 'Congo', 'Afrique', 'Brazzaville'),
    C(3, 'République démocratique du Congo', 'Afrique', 'Kinshasa'),
    C(192, 'Îles Cook', 'Océanie', 'Avarua'),
    C(25, 'Corée du Nord', 'Asie', 'Pyongyang'),
    C(5, 'Corée du Sud', 'Asie', 'Séoul'),
    C(139, 'Costa Rica', 'Amérique centrale', 'San José'),
    C(130, 'Côte dʻIvoire', 'Afrique', 'Yamoussoukro'),
    C(99, 'Croatie', 'Europe', 'Zagreb'),
    C(41, 'Cuba', 'Océanie', 'La Havane'),
    C(128, 'Danemark', 'Europe', 'Copenhague'),
    C(129, 'Djibouti', 'Afrique', 'Djibouti'),
    C(71, 'République dominicaine', 'Océanie', 'Saint-Domingue'),
    C(187, 'Dominique', 'Océanie', 'Roseau'),
    C(14, 'Égypte', 'Proche-Orient', 'Le Caire'),
    C(119, 'Émirats arabes unis', 'Proche-Orient', 'Abou Dhabi'),
    C(57, 'Équateur', 'Amérique du Sud', 'Quito'),
    C(123, 'Érythrée', 'Afrique', 'Asmara'),
    C(24, 'Espagne', 'Europe', 'Madrid'),
    C(133, 'Estonie', 'Europe', 'Tallinn'),
    C(116, 'États-Unis', 'Amérique du Nord', 'Washington'),
    C(28, 'Éthiopie', 'Afrique', 'Addis-Abeba'),
    C(165, 'Fidji', 'Océanie', 'Suva'),
    C(118, 'Finlande', 'Europe', 'Helsinki'),
    C(37, 'France', 'Europe', 'Paris'),
    C(122, 'Gabon', 'Afrique', 'Libreville'),
    C(178, 'Gambie', 'Afrique', 'Banjul'),
    C(79, 'Géorgie', 'Proche-Orient', 'Tbilissi'),
    C(53, 'Ghana', 'Afrique', 'Accra'),
    C(111, 'Grèce', 'Europe', 'Athènes'),
    C(190, 'Grenade', 'Océanie', 'Saint-Georges'),
    C(84, 'Guatemala', 'Amérique centrale', 'Guatemala'),
    C(61, 'Guinée', 'Afrique', 'Conakry'),
    C(131, 'Guinée-Bissau', 'Afrique', 'Bissau'),
    C(164, 'Guinée équatoriale', 'Afrique', 'Malabo'),
    C(157, 'Guyana', 'Amérique du Sud', 'Georgetown'),
    C(67, 'Haïti', 'Océanie', 'Port-au-Prince'),
    C(109, 'Honduras', 'Amérique centrale', 'Tegucigalpa'),
    C(48, 'Hongrie', 'Europe', 'Budapest'),
    C(148, 'Inde', 'Asie', 'New Delhi'),
    C(6, 'Indonésie', 'Asie', 'Jakarta'),
    C(15, 'Iraq', 'Proche-Orient', 'Bagdad'),
    C(12, 'Iran', 'Proche-Orient', 'Téhéran'),
    C(82, 'Ireland', 'Europe', 'Dublin	'),
    C(160, 'Islande', 'Europe', 'Reykjavík'),
    C(90, 'Israel', 'Proche-Orient', 'Jerusalem'),
    C(30, 'Italie', 'Europe', 'Rome'),
    C(115, 'Jamaïque', 'Océanie', 'Kingston'),
    C(2, 'Japon', 'Asie', 'Tokyo'),
    C(34, 'Jordanie', 'Proche-Orient', 'Amman'),
    C(94, 'Kazakhstan', 'Asie', 'Noursoultan'),
    C(27, 'Kenya', 'Afrique', 'Nairobi'),
    C(93, 'Kirghizstan', 'Asie', 'Bichkek'),
    C(179, 'Kiribati', 'Océanie', 'Tarawa'),
    C(152, 'Kosovo', 'Europe', 'Pristina'),
    C(69, 'Koweït', 'Proche-Orient', 'Koweït'),
    C(141, 'Laos', 'Asie', 'Vientiane'),
    C(143, 'Lesotho', 'Afrique', 'Maseru	'),
    C(114, 'Lettonie', 'Europe', 'Riga	'),
    C(56, 'Liban', 'Proche-Orient', 'Beyrouth'),
    C(83, 'Liberia', 'Afrique', 'Monrovia'),
    C(68, 'Libye', 'Afrique', 'Tripoli'),
    C(193, 'Liechtenstein', 'Europe', 'Vaduz'),
    C(121, 'Lituanie', 'Europe', 'Vilnius'),
    C(167, 'Luxembourg', 'Europe', 'Luxembourg'),
    C(127, 'Macédoine', 'Europe', 'Skopje'),
    C(55, 'Madagascar', 'Afrique', 'Antananarivo'),
    C(62, 'Malaisie', 'Asie', 'Kuala Lumpur'),
    C(89, 'Malawi', 'Afrique', 'Lilongwe'),
    C(162, 'Maldives', 'Océanie', 'Malé'),
    C(65, 'Mali', 'Afrique', 'Bamako'),
    C(45, 'Maroc', 'Afrique', 'Rabat'),
    C(182, 'Îles Marshall', 'Océanie', 'Delap-Uliga-Darrit'),
    C(154, 'Maurice', 'Océanie', 'Port-Louis'),
    C(112, 'Mauritanie', 'Afrique', 'Nouakchott'),
    C(8, 'Mexique', 'Amérique du Nord', 'Mexico'),
    C(189, 'Micronésie', 'Océanie', 'Palikir'),
    C(102, 'Moldavie', 'Europe', 'Chișinău'),
    C(177, 'Monaco', 'Europe', 'Monte-Carlo'),
    C(88, 'Mongolie', 'Asie', 'Oulan-Bator'),
    C(153, 'Monténégro', 'Europe', 'Podgorica'),
    C(77, 'Mozambique', 'Afrique', 'Maputo'),
    C(147, 'Namibie', 'Afrique', 'Windhoek'),
    C(197, 'Nauru', 'Océanie', 'Yaren'),
    C(97, 'Népal', 'Asie', 'Katmandou'),
    C(86, 'Nicaragua', 'Amérique centrale', 'Managua'),
    C(101, 'Niger', 'Afrique', 'Niamey'),
    C(104, 'Nigeria', 'Afrique', 'Abuja'),
    C(117, 'Norvège', 'Europe', 'Oslo'),
    C(136, 'Nouvelle-Zélande', 'Océanie', 'Wellington'),
    C(100, 'Oman', 'Proche-Orient', 'Mascate'),
    C(52, 'Ouganda', 'Afrique', 'Kampala'),
    C(38, 'Ouzbékistan', 'Asie', 'Tachkent'),
    C(85, 'Pakistan', 'Asie', 'Islamabad'),
    C(200, 'Palaos', 'Océanie', 'Melekeok'),
    C(96, 'Panama', 'Amérique centrale', 'Panama'),
    C(140, 'Papouasie-Nouvelle-Guinée', 'Océanie', 'Port Moresby'),
    C(126, 'Paraguay', 'Amérique du Sud', 'Asunción'),
    C(98, 'Pays-Bas', 'Europe', 'Amsterdam'),
    C(10, 'Pérou', 'Amérique du Sud', 'Lima'),
    C(51, 'Philippines', 'Asie', 'Manille'),
    C(49, 'Pologne', 'Europe', 'Varsovie'),
    C(124, 'Portugal', 'Europe', 'Lisbonne'),
    C(59, 'Qatar', 'Proche-Orient', 'Doha'),
    C(43, 'Roumanie', 'Europe', 'Bucarest'),
    C(9, 'Royaume-Uni', 'Europe', 'Londres'),
    C(4, 'Russie', 'Europe', 'Moscou'),
    C(113, 'Rwanda', 'Afrique', 'Kigali'),
    C(188, 'Saint-Christophe-et-Niévès', 'Océanie', 'Basseterre'),
    C(194, 'Saint-Marin', 'Europe', 'Saint-Marin'),
    C(174, 'Saint-Vincent-et-les-Grenadines', 'Océanie', 'Kingstown'),
    C(168, 'Sainte-Lucie', 'Océanie', 'Castries'),
    C(170, 'Salomon', 'Océanie', 'Honiara'),
    C(125, 'El Salvador', 'Amérique centrale', 'San Salvador'),
    C(175, 'Samoa', 'Océanie', 'Apia'),
    C(172, 'São Tomé-et-Principe', 'Océanie', 'São Tome'),
    C(80, 'Sénégal', 'Afrique', 'Dakar'),
    C(70, 'Serbie', 'Europe', 'Belgrade'),
    C(180, 'Seychelles', 'Océanie', 'Victoria'),
    C(78, 'Sierra Leone', 'Afrique', 'Freetown'),
    C(16, 'Singapour', 'Asie', 'Singapour'),
    C(132, 'Slovaquie', 'Europe', 'Bratislava'),
    C(145, 'Slovénie', 'Europe', 'Ljubljana'),
    C(72, 'Somalie', 'Afrique', 'Mogadiscio'),
    C(47, 'Soudan', 'Afrique', 'Khartoum'),
    C(137, 'Sud-Soudan', 'Afrique', 'Djouba'),
    C(159, 'Sri Lanka', 'Asie', 'Sri Jayawardenapura Kotte'),
    C(40, 'Suède', 'Europe', 'Stockholm'),
    C(156, 'Suisse', 'Europe', 'Berne'),
    C(146, 'Suriname', 'Amérique du Sud', 'Paramaribo'),
    C(166, 'Swaziland', 'Afrique', 'Mbabane'),
    C(22, 'Syrie', 'Proche-Orient', 'Damas'),
    C(120, 'Tadjikistan', 'Asie', 'Douchanbé'),
    C(32, 'Taïwan', 'Asie', 'Taipei'),
    C(142, 'Tanzanie', 'Afrique', 'Dodoma'),
    C(108, 'Tchad', 'Afrique', 'NʻDjaména'),
    C(66, 'République tchèque', 'Europe', 'Prague'),
    C(11, 'Thaïlande', 'Asie', 'Bangkok'),
    C(171, 'Timor-Oriental', 'Asie', 'Dili'),
    C(95, 'Togo', 'Afrique', 'Lomé'),
    C(185, 'Tonga', 'Océanie', 'Nukuʻalofa'),
    C(173, 'Trinidad-et-Tobago', 'Océanie', 'Port dʻEspagne'),
    C(106, 'Tunisie', 'Afrique', 'Tunis'),
    C(107, 'Turkménistan', 'Asie', 'Achgabat'),
    C(17, 'Turquie', 'Proche-Orient', 'Ankara'),
    C(195, 'Tuvalu', 'Océanie', 'Funafuti'),
    C(31, 'Ukraine', 'Europe', 'Kiev'),
    C(63, 'Uruguay', 'Amérique du Sud', 'Montevideo'),
    C(176, 'Vanuatu', 'Océanie', 'Port Vila'),
    C(198, 'Vatican', 'Europe', 'Vatican'),
    C(44, 'Venezuela', 'Amérique du Sud', 'Caracas'),
    C(23, 'Viêt Nam', 'Asie', 'Hanoï'),
    C(60, 'Yémen', 'Proche-Orient', 'Sanaa'),
    C(64, 'Zambie', 'Afrique', 'Lusaka'),
    C(58, 'Zimbabwe', 'Afrique', 'Harare'),
  ];

  final List<C> dataEn = [
    C(26, 'Afghanistan', 'Middle East', 'Kabul'),
    C(36, 'South Africa', 'Africa', 'Pretoria'),
    C(105, 'Albania', 'Europe', 'Tirana'),
    C(20, 'Algeria', 'Africa', 'Algiers'),
    C(21, 'Germany', 'Europe', 'Berlin'),
    C(183, 'Andorra', 'Europe', 'Andorra la Vella'),
    C(35, 'Angola', 'Africa', 'Luanda'),
    C(184, 'Antigua and Barbuda', 'Oceania', 'Saint Johns'),
    C(19, 'Saudi Arabia', 'Middle East', 'Riyadh'),
    C(29, 'Argentina', 'South America', 'Buenos Aires'),
    C(76, 'Armenia', 'Middle East', 'Yerevan'),
    C(138, 'Australia', 'Oceania', 'Canberra'),
    C(46, 'Austria', 'Europe', 'Vienna'),
    C(39, 'Azerbaijan', 'Middle East', 'Baku'),
    C(149, 'Bahamas', 'Oceania', 'Nassau'),
    C(155, 'Bahrain', 'Middle East', 'Manama'),
    C(7, 'Bangladesh', 'Asia', 'Dhaka'),
    C(161, 'Barbados', 'Oceania', 'Bridgetown'),
    C(74, 'Belgium', 'Europe', 'Brussels'),
    C(186, 'Belize', 'Central America', 'Belmopan'),
    C(151, 'Benin', 'Africa', 'Porto-Novo'),
    C(163, 'Bhutan', 'Asia', 'Thimphu'),
    C(50, 'Belarus', 'Europe', 'Minsk'),
    C(87, 'Burma (Myanmar)', 'Asia', 'Naypyidaw'),
    C(92, 'Bolivia', 'South America', 'La Paz'),
    C(135, 'Bosnia and Herzegovina', 'Europe', 'Sarajevo'),
    C(150, 'Botswana', 'Africa', 'Gaborone'),
    C(33, 'Brazil', 'South America', 'Brasilia'),
    C(181, 'Brunei', 'Asia', 'Bandar Seri Begawan'),
    C(134, 'Bulgaria', 'Europe', 'Sofia'),
    C(81, 'Burkina Faso', 'Africa', 'Ouagadougou'),
    C(73, 'Burundi', 'Africa', 'Gitega'),
    C(42, 'Cambodia', 'Asia', 'Phnom Penh'),
    C(54, 'Cameroon', 'Africa', 'Yaoundé'),
    C(91, 'Canada', 'North America', 'Ottawa'),
    C(158, 'Cape Verde', 'Oceania', 'Praia'),
    C(110, 'Central African Republic', 'Africa', 'Bangui'),
    C(18, 'Chile', 'South America', 'Santiago'),
    C(1, 'China', 'Asia', 'Beijing'),
    C(144, 'Cyprus', 'Middle East', 'Nicosia'),
    C(13, 'Colombia', 'South America', 'Bogota'),
    C(169, 'Comoros', 'Oceania', 'Moroni'),
    C(75, 'Congo', 'Africa', 'Brazzaville'),
    C(3, 'Democratic Republic of Congo', 'Africa', 'Kinshasa'),
    C(192, 'Cook Islands', 'Oceania', 'Avarua'),
    C(25, 'North Korea', 'Asia', 'Pyongyang'),
    C(5, 'South Korea', 'Asia', 'Seoul'),
    C(139, 'Costa Rica', 'Central America', 'San José'),
    C(130, 'Côte dʻIvoire', 'Africa', 'Yamoussoukro'),
    C(99, 'Croatia', 'Europe', 'Zagreb'),
    C(41, 'Cuba', 'Oceania', 'Havana'),
    C(128, 'Denmark', 'Europe', 'Copenhagen'),
    C(129, 'Djibouti', 'Africa', 'Djibouti'),
    C(71, 'Dominican Republic', 'Oceania', 'Santo Domingo'),
    C(187, 'Dominica', 'Oceania', 'Roseau'),
    C(14, 'Egypt', 'Middle East', 'Cairo'),
    C(119, 'United Arab Emirates', 'Middle East', 'Abu Dhabi'),
    C(57, 'Ecuador', 'South America', 'Quito'),
    C(123, 'Eritrea', 'Africa', 'Asmara'),
    C(24, 'Spain', 'Europe', 'Madrid'),
    C(133, 'Estonia', 'Europe', 'Tallinn'),
    C(116, 'United States', 'North America', 'Washington'),
    C(28, 'Ethiopia', 'Africa', 'Addis Ababa'),
    C(165, 'Fiji', 'Oceania', 'Suva'),
    C(118, 'Finland', 'Europe', 'Helsinki'),
    C(37, 'France', 'Europe', 'Paris'),
    C(122, 'Gabon', 'Africa', 'Libreville'),
    C(178, 'Gambia', 'Africa', 'Banjul'),
    C(79, 'Georgia', 'Middle East', 'Tbilisi'),
    C(53, 'Ghana', 'Africa', 'Accra'),
    C(111, 'Greece', 'Europe', 'Athens'),
    C(190, 'Grenada', 'Oceania', 'Saint-Georges'),
    C(84, 'Guatemala', 'Central America', 'Guatemala'),
    C(61, 'Guinea', 'Africa', 'Conakry'),
    C(131, 'Guinea-Bissau', 'Africa', 'Bissau'),
    C(164, 'Equatorial Guinea', 'Africa', 'Malabo'),
    C(157, 'Guyana', 'South America', 'Georgetown'),
    C(67, 'Haiti', 'Oceania', 'Port-au-Prince'),
    C(109, 'Honduras', 'Central America', 'Tegucigalpa'),
    C(48, 'Hungary', 'Europe', 'Budapest'),
    C(148, 'India', 'Asia', 'New Delhi'),
    C(6, 'Indonesia', 'Asia', 'Jakarta'),
    C(15, 'Iraq', 'Middle East', 'Baghdad'),
    C(12, 'Iran', 'Middle East', 'Tehran'),
    C(82, 'Ireland', 'Europe', 'Dublin'),
    C(160, 'Iceland', 'Europe', 'Reykjavík'),
    C(90, 'Israel', 'Middle East', 'Jerusalem'),
    C(30, 'Italy', 'Europe', 'Rome'),
    C(115, 'Jamaica', 'Oceania', 'Kingston'),
    C(2, 'Japan', 'Asia', 'Tokyo'),
    C(34, 'Jordan', 'Middle East', 'Amman'),
    C(94, 'Kazakhstan', 'Asia', 'Noursoultan'),
    C(27, 'Kenya', 'Africa', 'Nairobi'),
    C(93, 'Kyrgyzstan', 'Asia', 'Bishkek'),
    C(179, 'Kiribati', 'Oceania', 'Tarawa'),
    C(152, 'Kosovo', 'Europe', 'Pristina'),
    C(69, 'Kuwait', 'Middle East', 'Kuwait'),
    C(141, 'Laos', 'Asia', 'Vientiane'),
    C(143, 'Lesotho', 'Africa', 'Maseru'),
    C(114, 'Latvia', 'Europe', 'Riga'),
    C(56, 'Lebanon', 'Middle East', 'Beirut'),
    C(83, 'Liberia', 'Africa', 'Monrovia'),
    C(68, 'Libya', 'Africa', 'Tripoli'),
    C(193, 'Liechtenstein', 'Europe', 'Vaduz'),
    C(121, 'Lithuania', 'Europe', 'Vilnius'),
    C(167, 'Luxembourg', 'Europe', 'Luxembourg'),
    C(127, 'Macedonia', 'Europe', 'Skopje'),
    C(55, 'Madagascar', 'Africa', 'Antananarivo'),
    C(62, 'Malaysia', 'Asia', 'Kuala Lumpur'),
    C(89, 'Malawi', 'Africa', 'Lilongwe'),
    C(162, 'Maldives', 'Oceania', 'Malé'),
    C(65, 'Mali', 'Africa', 'Bamako'),
    C(45, 'Morocco', 'Africa', 'Rabat'),
    C(182, 'Marshall Islands', 'Oceania', 'Delap-Uliga-Darrit'),
    C(154, 'Mauritius', 'Oceania', 'Port-Louis'),
    C(112, 'Mauritania', 'Africa', 'Nouakchott'),
    C(8, 'Mexico', 'North America', 'Mexico'),
    C(189, 'Micronesia', 'Oceania', 'Palikir'),
    C(102, 'Moldavia', 'Europe', 'Chișinău'),
    C(177, 'Monaco', 'Europe', 'Monte-Carlo'),
    C(88, 'Mongolia', 'Asia', 'Ulan Bator'),
    C(153, 'Montenegro', 'Europe', 'Podgorica'),
    C(77, 'Mozambique', 'Africa', 'Maputo'),
    C(147, 'Namibia', 'Africa', 'Windhoek'),
    C(197, 'Nauru', 'Oceania', 'Yaren'),
    C(97, 'Nepal', 'Asia', 'Kathmandu'),
    C(86, 'Nicaragua', 'Central America', 'Managua'),
    C(101, 'Niger', 'Africa', 'Niamey'),
    C(104, 'Nigeria', 'Africa', 'Abuja'),
    C(117, 'Norway', 'Europe', 'Oslo'),
    C(136, 'New Zealand', 'Oceania', 'Wellington'),
    C(100, 'Oman', 'Middle East', 'Muscat'),
    C(52, 'Uganda', 'Africa', 'Kampala'),
    C(38, 'Uzbekistan', 'Asia', 'Tashkent'),
    C(85, 'Pakistan', 'Asia', 'Islamabad'),
    C(200, 'Palau', 'Oceania', 'Melekeok'),
    C(96, 'Panama', 'Central America', 'Panama'),
    C(140, 'Papua New Guinea', 'Oceania', 'Port Moresby'),
    C(126, 'Paraguay', 'South America', 'Asunción'),
    C(98, 'Netherlands', 'Europe', 'Amsterdam'),
    C(10, 'Peru', 'South America', 'Lima'),
    C(51, 'Philippines', 'Asia', 'Manila'),
    C(49, 'Poland', 'Europe', 'Warsaw'),
    C(124, 'Portugal', 'Europe', 'Lisbon'),
    C(59, 'Qatar', 'Middle East', 'Doha'),
    C(43, 'Romania', 'Europe', 'Bucharest'),
    C(9, 'United Kingdom', 'Europe', 'London'),
    C(4, 'Russia', 'Europe', 'Moscow'),
    C(113, 'Rwanda', 'Africa', 'Kigali'),
    C(188, 'Saint Kitts and Nevis', 'Oceania', 'Basseterre'),
    C(194, 'San Marino', 'Europe', 'San Marino'),
    C(174, 'Saint Vincent and the Grenadines', 'Oceania', 'Kingstown'),
    C(168, 'Saint Lucia', 'Oceania', 'Castries'),
    C(170, 'Solomon', 'Oceania', 'Honiara'),
    C(125, 'El Salvador', 'Central America', 'San Salvador'),
    C(175, 'Samoa', 'Oceania', 'Apia'),
    C(172, 'São Tomé and Príncipe', 'Oceania', 'São Tome'),
    C(80, 'Senegal', 'Africa', 'Dakar'),
    C(70, 'Serbia', 'Europe', 'Belgrade'),
    C(180, 'Seychelles', 'Oceania', 'Victoria'),
    C(78, 'Sierra Leone', 'Africa', 'Freetown'),
    C(16, 'Singapore', 'Asia', 'Singapore'),
    C(132, 'Slovakia', 'Europe', 'Bratislava'),
    C(145, 'Slovenia', 'Europe', 'Ljubljana'),
    C(72, 'Somalia', 'Africa', 'Mogadishu'),
    C(47, 'Sudan', 'Africa', 'Khartoum'),
    C(137, 'South Sudan', 'Africa', 'Djouba'),
    C(159, 'Sri Lanka', 'Asia', 'Sri Jayawardenapura Kotte'),
    C(40, 'Sweden', 'Europe', 'Stockholm'),
    C(156, 'Switzerland', 'Europe', 'Berne'),
    C(146, 'Suriname', 'South America', 'Paramaribo'),
    C(166, 'Swaziland', 'Africa', 'Mbabane'),
    C(22, 'Syria', 'Middle East', 'Damascus'),
    C(120, 'Tajikistan', 'Asia', 'Dushanbe'),
    C(32, 'Taiwan', 'Asia', 'Taipei'),
    C(142, 'Tanzania', 'Africa', 'Dodoma'),
    C(108, 'Chad', 'Africa', 'NʻDjaména'),
    C(66, 'Czech Republic', 'Europe', 'Prague'),
    C(11, 'Thailand', 'Asia', 'Bangkok'),
    C(171, 'East Timor', 'Asia', 'Dili'),
    C(95, 'Togo', 'Africa', 'Lomé'),
    C(185, 'Tonga', 'Oceania', 'Nukuʻalofa'),
    C(173, 'Trinidad and Tobago', 'Oceania', 'Port of Spain'),
    C(106, 'Tunisia', 'Africa', 'Tunis'),
    C(107, 'Turkmenistan', 'Asia', 'Ashgabat'),
    C(17, 'Turkey', 'Middle East', 'Ankara'),
    C(195, 'Tuvalu', 'Oceania', 'Funafuti'),
    C(31, 'Ukraine', 'Europe', 'Kiev'),
    C(63, 'Uruguay', 'South America', 'Montevideo'),
    C(176, 'Vanuatu', 'Oceania', 'Port Vila'),
    C(198, 'Vatican', 'Europe', 'Vatican'),
    C(44, 'Venezuela', 'South America', 'Caracas'),
    C(23, 'Vietnam', 'Asia', 'Hanoi'),
    C(60, 'Yemen', 'Middle East', 'Sanaa'),
    C(64, 'Zambia', 'Africa', 'Lusaka'),
    C(58, 'Zimbabwe', 'Africa', 'Harare'),
  ];

  final List<C> dataDe = [
    C(26, "Afghanistan", "Naher Osten", "Kabul"),
    C(36, "Südafrika", "Afrika", "Pretoria"),
    C(105, "Albanien", "Europa", "Tirana"),
    C(20, "Algerien", "Afrika", "Algier"),
    C(21, "Deutschland", "Europa", "Berlin"),
    C(183, "Andorra", "Europa", "Andorra la Vella"),
    C(35, "Angola", "Afrika", "Luanda"),
    C(184, "Antigua und Barbuda", "Ozeanien", "Saint Johns"),
    C(19, "Saudi-Arabien", "Naher Osten", "Riad"),
    C(29, "Argentinien", "Südamerika", "Buenos Aires"),
    C(76, "Armenien", "Naher Osten", "Eriwan"),
    C(138, "Australien", "Ozeanien", "Canberra"),
    C(46, "Österreich", "Europa", "Wien"),
    C(39, "Aserbaidschan", "Naher Osten", "Baku"),
    C(149, "Bahamas", "Ozeanien", "Nassau"),
    C(155, "Bahrain", "Naher Osten", "Manama"),
    C(7, "Bangladesch", "Asien", "Dhaka"),
    C(161, "Barbados", "Ozeanien", "Bridgetown"),
    C(74, "Belgien", "Europa", "Brüssel"),
    C(186, "Belize", "Mittelamerika", "Belmopan"),
    C(151, "Benin", "Afrika", "Porto-Novo"),
    C(163, "Bhutan", "Asien", "Thimphu"),
    C(50, "Weißrussland", "Europa", "Minsk"),
    C(87, "Burma (Myanmar)", "Asien", "Naypyidaw"),
    C(92, "Bolivien", "Südamerika", "La Paz"),
    C(135, "Bosnien und Herzegowina", "Europa", "Sarajevo"),
    C(150, "Botswana", "Afrika", "Gaborone"),
    C(33, "Brasilien", "Südamerika", "Brasilia"),
    C(181, "Brunei", "Asien", "Bandar Seri Begawan"),
    C(134, "Bulgarien", "Europa", "Sofia"),
    C(81, "Burkina Faso", "Afrika", "Ouagadougou"),
    C(73, "Burundi", "Afrika", "Gitega"),
    C(42, "Kambodscha", "Asien", "Phnom Penh"),
    C(54, "Kamerun", "Afrika", "Yaoundé"),
    C(91, "Kanada", "Nordamerika", "Ottawa"),
    C(158, "Kap Verde", "Ozeanien", "Praia"),
    C(110, "Zentralafrikanische Republik", "Afrika", "Bangui"),
    C(18, "Chile", "Südamerika", "Santiago"),
    C(1, "China", "Asien", "Peking"),
    C(144, "Zypern", "Naher Osten", "Nikosia"),
    C(13, "Kolumbien", "Südamerika", "Bogota"),
    C(169, "Komoren", "Ozeanien", "Moroni"),
    C(75, "Kongo", "Afrika", "Brazzaville"),
    C(3, "Demokratische Republik Kongo", "Afrika", "Kinshasa"),
    C(192, "Cookinseln", "Ozeanien", "Avarua"),
    C(25, "Nordkorea", "Asien", "Pjöngjang"),
    C(5, "Südkorea", "Asien", "Seoul"),
    C(139, "Costa Rica", "Mittelamerika", "San José"),
    C(130, "Côte d'Ivoire", "Afrika", "Yamoussoukro"),
    C(99, "Kroatien", "Europa", "Zagreb"),
    C(41, "Kuba", "Ozeanien", "Havanna"),
    C(128, "Dänemark", "Europa", "Kopenhagen"),
    C(129, "Dschibuti", "Afrika", "Dschibuti"),
    C(71, "Dominikanische Republik", "Ozeanien", "Santo Domingo"),
    C(187, "Dominica", "Ozeanien", "Roseau"),
    C(14, "Ägypten", "Naher Osten", "Kairo"),
    C(119, "Vereinigte Arabische Emirate", "Naher Osten", "Abu Dhabi"),
    C(57, "Ecuador", "Südamerika", "Quito"),
    C(123, "Eritrea", "Afrika", "Asmara"),
    C(24, "Spanien", "Europa", "Madrid"),
    C(133, "Estland", "Europa", "Tallinn"),
    C(116, "USA", "Nordamerika", "Washington"),
    C(28, "Äthiopien", "Afrika", "Addis Abeba"),
    C(165, "Fidschi", "Ozeanien", "Suva"),
    C(118, "Finnland", "Europa", "Helsinki"),
    C(37, "Frankreich", "Europa", "Paris"),
    C(122, "Gabun", "Afrika", "Libreville"),
    C(178, "Gambia", "Afrika", "Banjul"),
    C(79, "Georgien", "Naher Osten", "Tiflis"),
    C(53, "Ghana", "Afrika", "Accra"),
    C(111, "Griechenland", "Europa", "Athen"),
    C(190, "Grenada", "Ozeanien", "Saint-Georges"),
    C(84, "Guatemala", "Mittelamerika", "Guatemala"),
    C(61, "Guinea", "Afrika", "Conakry"),
    C(131, "Guinea-Bissau", "Afrika", "Bissau"),
    C(164, "Äquatorialguinea", "Afrika", "Malabo"),
    C(157, "Guyana", "Südamerika", "Georgetown"),
    C(67, "Haiti", "Ozeanien", "Port-au-Prince"),
    C(109, "Honduras", "Mittelamerika", "Tegucigalpa"),
    C(48, "Ungarn", "Europa", "Budapest"),
    C(148, "Indien", "Asien", "Neu-Delhi"),
    C(6, "Indonesien", "Asien", "Jakarta"),
    C(15, "Irak", "Naher Osten", "Bagdad"),
    C(12, "Iran", "Naher Osten", "Teheran"),
    C(82, "Irland", "Europa", "Dublin"),
    C(160, "Island", "Europa", "Reykjavík"),
    C(90, "Israel", "Naher Osten", "Jerusalem"),
    C(30, "Italien", "Europa", "Rom"),
    C(115, "Jamaika", "Ozeanien", "Kingston"),
    C(2, "Japan", "Asien", "Tokio"),
    C(34, "Jordanien", "Naher Osten", "Amman"),
    C(94, "Kasachstan", "Asien", "Noursoultan"),
    C(27, "Kenia", "Afrika", "Nairobi"),
    C(93, "Kirgisistan", "Asien", "Bischkek"),
    C(179, "Kiribati", "Ozeanien", "Tarawa"),
    C(152, "Kosovo", "Europa", "Pristina"),
    C(69, "Kuwait", "Naher Osten", "Kuwait"),
    C(141, "Laos", "Asien", "Vientiane"),
    C(143, "Lesotho", "Afrika", "Maseru"),
    C(114, "Lettland", "Europa", "Riga"),
    C(56, "Libanon", "Naher Osten", "Beirut"),
    C(83, "Liberia", "Afrika", "Monrovia"),
    C(68, "Libyen", "Afrika", "Tripolis"),
    C(193, "Liechtenstein", "Europa", "Vaduz"),
    C(121, "Litauen", "Europa", "Vilnius"),
    C(167, "Luxemburg", "Europa", "Luxemburg"),
    C(127, "Mazedonien", "Europa", "Skopje"),
    C(55, "Madagaskar", "Afrika", "Antananarivo"),
    C(62, "Malaysia", "Asien", "Kuala Lumpur"),
    C(89, "Malawi", "Afrika", "Lilongwe"),
    C(162, "Malediven", "Ozeanien", "Malé"),
    C(65, "Mali", "Afrika", "Bamako"),
    C(45, "Marokko", "Afrika", "Rabat"),
    C(182, "Marshallinseln", "Ozeanien", "Delap-Uliga-Darrit"),
    C(154, "Mauritius", "Ozeanien", "Port-Louis"),
    C(112, "Mauretanien", "Afrika", "Nouakchott"),
    C(8, "Mexiko", "Nordamerika", "Mexiko"),
    C(189, "Mikronesien", "Ozeanien", "Palikir"),
    C(102, "Moldawien", "Europa", "Chișinău"),
    C(177, "Monaco", "Europa", "Monte-Carlo"),
    C(88, "Mongolei", "Asien", "Ulan Bator"),
    C(153, "Montenegro", "Europa", "Podgorica"),
    C(77, "Mosambik", "Afrika", "Maputo"),
    C(147, "Namibia", "Afrika", "Windhoek"),
    C(197, "Nauru", "Ozeanien", "Yaren"),
    C(97, "Nepal", "Asien", "Kathmandu"),
    C(86, "Nicaragua", "Mittelamerika", "Managua"),
    C(101, "Niger", "Afrika", "Niamey"),
    C(104, "Nigeria", "Afrika", "Abuja"),
    C(117, "Norwegen", "Europa", "Oslo"),
    C(136, "Neuseeland", "Ozeanien", "Wellington"),
    C(100, "Oman", "Naher Osten", "Maskat"),
    C(52, "Uganda", "Afrika", "Kampala"),
    C(38, "Usbekistan", "Asien", "Taschkent"),
    C(85, "Pakistan", "Asien", "Islamabad"),
    C(200, "Palau", "Ozeanien", "Melekeok"),
    C(96, "Panama", "Mittelamerika", "Panama"),
    C(140, "Papua-Neuguinea", "Ozeanien", "Port Moresby"),
    C(126, "Paraguay", "Südamerika", "Asunción"),
    C(98, "Niederlande", "Europa", "Amsterdam"),
    C(10, "Peru", "Südamerika", "Lima"),
    C(51, "Philippinen", "Asien", "Manila"),
    C(49, "Polen", "Europa", "Warschau"),
    C(124, "Portugal", "Europa", "Lissabon"),
    C(59, "Katar", "Naher Osten", "Doha"),
    C(43, "Rumänien", "Europa", "Bukarest"),
    C(9, "Vereinigtes Königreich", "Europa", "London"),
    C(4, "Russland", "Europa", "Moskau"),
    C(113, "Ruanda", "Afrika", "Kigali"),
    C(188, "St. Kitts und Nevis", "Ozeanien", "Basseterre"),
    C(194, "San Marino", "Europa", "San Marino"),
    C(174, "St. Vincent und die Grenadinen", "Ozeanien", "Kingstown"),
    C(168, "St. Lucia", "Ozeanien", "Castries"),
    C(170, "Solomon", "Ozeanien", "Honiara"),
    C(125, "El Salvador", "Mittelamerika", "San Salvador"),
    C(175, "Samoa", "Ozeanien", "Apia"),
    C(172, "São Tomé und Príncipe", "Ozeanien", "São Tome"),
    C(80, "Senegal", "Afrika", "Dakar"),
    C(70, "Serbien", "Europa", "Belgrad"),
    C(180, "Seychellen", "Ozeanien", "Victoria"),
    C(78, "Sierra Leone", "Afrika", "Freetown"),
    C(16, "Singapur", "Asien", "Singapur"),
    C(132, "Slowakei", "Europa", "Bratislava"),
    C(145, "Slowenien", "Europa", "Ljubljana"),
    C(72, "Somalia", "Afrika", "Mogadischu"),
    C(47, "Sudan", "Afrika", "Khartum"),
    C(137, "Südsudan", "Afrika", "Djouba"),
    C(159, "Sri Lanka", "Asien", "Sri Jayawardenapura Kotte"),
    C(40, "Schweden", "Europa", "Stockholm"),
    C(156, "Schweiz", "Europa", "Bern"),
    C(146, "Suriname", "Südamerika", "Paramaribo"),
    C(166, "Swasiland", "Afrika", "Mbabane"),
    C(22, "Syrien", "Naher Osten", "Damaskus"),
    C(120, "Tadschikistan", "Asien", "Duschanbe"),
    C(32, "Taiwan", "Asien", "Taipeh"),
    C(142, "Tansania", "Afrika", "Dodoma"),
    C(108, "Tschad", "Afrika", "Njaména"),
    C(66, "Tschechische Republik", "Europa", "Prag"),
    C(11, "Thailand", "Asien", "Bangkok"),
    C(171, "Osttimor", "Asien", "Dili"),
    C(95, "Togo", "Afrika", "Lomé"),
    C(185, "Tonga", "Ozeanien", "Nukuʻalofa"),
    C(173, "Trinidad und Tobago", "Ozeanien", "Hafen von Spanien"),
    C(106, "Tunesien", "Afrika", "Tunis"),
    C(107, "Turkmenistan", "Asien", "Aschgabat"),
    C(17, "Türkei", "Naher Osten", "Ankara"),
    C(195, "Tuvalu", "Ozeanien", "Funafuti"),
    C(31, "Ukraine", "Europa", "Kiew"),
    C(63, "Uruguay", "Südamerika", "Montevideo"),
    C(176, "Vanuatu", "Ozeanien", "Port Vila"),
    C(198, "Vatikan", "Europa", "Vatikan"),
    C(44, "Venezuela", "Südamerika", "Caracas"),
    C(23, "Vietnam", "Asien", "Hanoi"),
    C(60, "Jemen", "Naher Osten", "Sanaa"),
    C(64, "Sambia", "Afrika", "Lusaka"),
    C(58, "Simbabwe", "Afrika", "Harare"),
  ];

  final List<C> dataEs = [
    C(26, 'Afganistán', 'Medio Oriente', 'Kabul'),
    C(36, 'Sudáfrica', 'África', 'Pretoria'),
    C(105, 'Albania', 'Europa', 'Tirana'),
    C(20, 'Argelia', 'África', 'Argel'),
    C(21, 'Alemania', 'Europa', 'Berlín'),
    C(183, 'Andorra', 'Europa', 'Andorra la Vella'),
    C(35, 'Angola', 'África', 'Luanda'),
    C(184, 'Antigua y Barbuda', 'Oceanía', 'Saint Johns'),
    C(19, 'Arabia Saudita', 'Medio Oriente', 'Riyadh'),
    C(29, 'Argentina', 'Sudamérica', 'Buenos Aires'),
    C(76, 'Armenia', 'Medio Oriente', 'Ereván'),
    C(138, 'Australia', 'Oceanía', 'Canberra'),
    C(46, 'Austria', 'Europa', 'Viena'),
    C(39, 'Azerbaiyán', 'Medio Oriente', 'Bakú'),
    C(149, 'Bahamas', 'Oceanía', 'Nassau'),
    C(155, 'Bahréin', 'Medio Oriente', 'Manama'),
    C(7, 'Bangladesh', 'Asia', 'Dhaka'),
    C(161, 'Barbados', 'Oceanía', 'Bridgetown'),
    C(74, 'Bélgica', 'Europa', 'Bruselas'),
    C(186, 'Belice', 'Centroamérica', 'Belmopán'),
    C(151, 'Benin', 'África', 'Porto-Novo'),
    C(163, 'Bután', 'Asia', 'Thimphu'),
    C(50, 'Bielorrusia', 'Europa', 'Minsk'),
    C(87, 'Birmania (Myanmar)', 'Asia', 'Naypyidaw'),
    C(92, 'Bolivia', 'Sudamérica', 'La Paz'),
    C(135, 'Bosnia y Herzegovina', 'Europa', 'Sarajevo'),
    C(150, 'Botswana', 'África', 'Gaborone'),
    C(33, 'Brasil', 'América del Sur', 'Brasilia'),
    C(181, 'Brunei', 'Asia', 'Bandar Seri Begawan'),
    C(134, 'Bulgaria', 'Europa', 'Sofía'),
    C(81, 'Burkina Faso', 'África', 'Uagadugú'),
    C(73, 'Burundi', 'África', 'Gitega'),
    C(42, 'Camboya', 'Asia', 'Phnom Penh'),
    C(54, 'Camerún', 'África', 'Yaundé'),
    C(91, 'Canadá', 'América del Norte', 'Ottawa'),
    C(158, 'Cabo Verde', 'Oceanía', 'Praia'),
    C(110, 'República Centroafricana', 'África', 'Bangui'),
    C(18, 'Chile', 'América del Sur', 'Santiago'),
    C(1, 'China', 'Asia', 'Beijing'),
    C(144, 'Chipre', 'Medio Oriente', 'Nicosia'),
    C(13, 'Colombia', 'América del Sur', 'Bogotá'),
    C(169, 'Comoras', 'Oceanía', 'Moroni'),
    C(75, 'Congo', 'África', 'Brazzaville'),
    C(3, 'República Democrática del Congo', 'África', 'Kinshasa'),
    C(192, 'Islas Cook', 'Oceanía', 'Avarua'),
    C(25, 'Corea del Norte', 'Asia', 'Pyongyang'),
    C(5, 'Corea del Sur', 'Asia', 'Seúl'),
    C(139, 'Costa Rica', 'Centroamérica', 'San José'),
    C(130, 'Côte dʻIvoire', 'África', 'Yamoussoukro'),
    C(99, 'Croacia', 'Europa', 'Zagreb'),
    C(41, 'Cuba', 'Oceanía', 'La Habana'),
    C(128, 'Dinamarca', 'Europa', 'Copenhague'),
    C(129, 'Djibouti', 'África', 'Djibouti'),
    C(71, 'República Dominicana', 'Oceanía', 'Santo Domingo'),
    C(187, 'Dominica', 'Oceanía', 'Roseau'),
    C(14, 'Egipto', 'Medio Oriente', 'El Cairo'),
    C(119, 'Emiratos Árabes Unidos', 'Medio Oriente', 'Abu Dhabi'),
    C(57, 'Ecuador', 'América del Sur', 'Quito'),
    C(123, 'Eritrea', 'África', 'Asmara'),
    C(24, 'España', 'Europa', 'Madrid'),
    C(133, 'Estonia', 'Europa', 'Tallin'),
    C(116, 'Estados Unidos', 'América del Norte', 'Washington'),
    C(28, 'Etiopía', 'África', 'Addis Abeba'),
    C(165, 'Fiji', 'Oceanía', 'Suva'),
    C(118, 'Finlandia', 'Europa', 'Helsinki'),
    C(37, 'Francia', 'Europa', 'París'),
    C(122, 'Gabón', 'África', 'Libreville'),
    C(178, 'Gambia', 'África', 'Banjul'),
    C(79, 'Georgia', 'Medio Oriente', 'Tbilisi'),
    C(53, 'Ghana', 'África', 'Accra'),
    C(111, 'Grecia', 'Europa', 'Atenas'),
    C(190, 'Granada', 'Oceanía', 'Saint-Georges'),
    C(84, 'Guatemala', 'Centroamérica', 'Guatemala'),
    C(61, 'Guinea', 'África', 'Conakry'),
    C(131, 'Guinea-Bissau', 'África', 'Bissau'),
    C(164, 'Guinea Ecuatorial', 'África', 'Malabo'),
    C(157, 'Guyana', 'Sudamérica', 'Georgetown'),
    C(67, 'Haití', 'Oceanía', 'Puerto Príncipe'),
    C(109, 'Honduras', 'Centroamérica', 'Tegucigalpa'),
    C(48, 'Hungría', 'Europa', 'Budapest'),
    C(148, 'India', 'Asia', 'Nueva Delhi'),
    C(6, 'Indonesia', 'Asia', 'Yakarta'),
    C(15, 'Irak', 'Medio Oriente', 'Bagdad'),
    C(12, 'Irán', 'Medio Oriente', 'Teherán'),
    C(82, 'Irlanda', 'Europa', 'Dublín'),
    C(160, 'Islandia', 'Europa', 'Reykjavík'),
    C(90, 'Israel', 'Medio Oriente', 'Jerusalén'),
    C(30, 'Italia', 'Europa', 'Roma'),
    C(115, 'Jamaica', 'Oceanía', 'Kingston'),
    C(2, 'Japón', 'Asia', 'Tokio'),
    C(34, 'Jordania', 'Medio Oriente', 'Ammán'),
    C(94, 'Kazajstán', 'Asia', 'Noursoultan'),
    C(27, 'Kenia', 'África', 'Nairobi'),
    C(93, 'Kirguistán', 'Asia', 'Bishkek'),
    C(179, 'Kiribati', 'Oceanía', 'Tarawa'),
    C(152, 'Kosovo', 'Europa', 'Pristina'),
    C(69, 'Kuwait', 'Medio Oriente', 'Kuwait'),
    C(141, 'Laos', 'Asia', 'Vientiane'),
    C(143, 'Lesoto', 'África', 'Maseru'),
    C(114, 'Letonia', 'Europa', 'Riga'),
    C(56, 'Líbano', 'Medio Oriente', 'Beirut'),
    C(83, 'Liberia', 'África', 'Monrovia'),
    C(68, 'Libia', 'África', 'Trípoli'),
    C(193, 'Liechtenstein', 'Europa', 'Vaduz'),
    C(121, 'Lituania', 'Europa', 'Vilnius'),
    C(167, 'Luxemburgo', 'Europa', 'Luxemburgo'),
    C(127, 'Macedonia', 'Europa', 'Skopje'),
    C(55, 'Madagascar', 'África', 'Antananarivo'),
    C(62, 'Malasia', 'Asia', 'Kuala Lumpur'),
    C(89, 'Malawi', 'África', 'Lilongwe'),
    C(162, 'Maldivas', 'Oceanía', 'Malé'),
    C(65, 'Malí', 'África', 'Bamako'),
    C(45, 'Marruecos', 'África', 'Rabat'),
    C(182, 'Islas Marshall', 'Oceanía', 'Delap-Uliga-Darrit'),
    C(154, 'Mauricio', 'Oceanía', 'Port-Louis'),
    C(112, 'Mauritania', 'África', 'Nouakchott'),
    C(8, 'México', 'América del Norte', 'México'),
    C(189, 'Micronesia', 'Oceanía', 'Palikir'),
    C(102, 'Moldavia', 'Europa', 'Chișinău'),
    C(177, 'Mónaco', 'Europa', 'Montecarlo'),
    C(88, 'Mongolia', 'Asia', 'Ulan Bator'),
    C(153, 'Montenegro', 'Europa', 'Podgorica'),
    C(77, 'Mozambique', 'África', 'Maputo'),
    C(147, 'Namibia', 'África', 'Windhoek'),
    C(197, 'Nauru', 'Oceanía', 'Yaren'),
    C(97, 'Nepal', 'Asia', 'Katmandú'),
    C(86, 'Nicaragua', 'Centroamérica', 'Managua'),
    C(101, 'Níger', 'África', 'Niamey'),
    C(104, 'Nigeria', 'África', 'Abuja'),
    C(117, 'Noruega', 'Europa', 'Oslo'),
    C(136, 'Nueva Zelanda', 'Oceanía', 'Wellington'),
    C(100, 'Omán', 'Medio Oriente', 'Mascate'),
    C(52, 'Uganda', 'África', 'Kampala'),
    C(38, 'Uzbekistán', 'Asia', 'Tashkent'),
    C(85, 'Pakistán', 'Asia', 'Islamabad'),
    C(200, 'Palau', 'Oceanía', 'Melekeok'),
    C(96, 'Panamá', 'Centroamérica', 'Panamá'),
    C(140, 'Papua Nueva Guinea', 'Oceanía', 'Port Moresby'),
    C(126, 'Paraguay', 'América del Sur', 'Asunción'),
    C(98, 'Holanda', 'Europa', 'Amsterdam'),
    C(10, 'Perú', 'América del Sur', 'Lima'),
    C(51, 'Filipinas', 'Asia', 'Manila'),
    C(49, 'Polonia', 'Europa', 'Varsovia'),
    C(124, 'Portugal', 'Europa', 'Lisboa'),
    C(59, 'Qatar', 'Medio Oriente', 'Doha'),
    C(43, 'Rumania', 'Europa', 'Bucarest'),
    C(9, 'Reino Unido', 'Europa', 'Londres'),
    C(4, 'Rusia', 'Europa', 'Moscú'),
    C(113, 'Ruanda', 'África', 'Kigali'),
    C(188, 'Saint Kitts y Nevis', 'Oceanía', 'Basseterre'),
    C(194, 'San Marino', 'Europa', 'San Marino'),
    C(174, 'San Vicente y las Granadinas', 'Oceanía', 'Kingstown'),
    C(168, 'Santa Lucía', 'Oceanía', 'Castries'),
    C(170, 'Salomón', 'Oceanía', 'Honiara'),
    C(125, 'El Salvador', 'Centroamérica', 'San Salvador'),
    C(175, 'Samoa', 'Oceanía', 'Apia'),
    C(172, 'Santo Tomé y Príncipe', 'Oceanía', 'Santo Tomé'),
    C(80, 'Senegal', 'África', 'Dakar'),
    C(70, 'Serbia', 'Europa', 'Belgrado'),
    C(180, 'Seychelles', 'Oceanía', 'Victoria'),
    C(78, 'Sierra Leona', 'África', 'Freetown'),
    C(16, 'Singapur', 'Asia', 'Singapur'),
    C(132, 'Eslovaquia', 'Europa', 'Bratislava'),
    C(145, 'Eslovenia', 'Europa', 'Ljubljana'),
    C(72, 'Somalia', 'África', 'Mogadiscio'),
    C(47, 'Sudán', 'África', 'Jartum'),
    C(137, 'Sudán del Sur', 'África', 'Djouba'),
    C(159, 'Sri Lanka', 'Asia', 'Sri Jayawardenapura Kotte'),
    C(40, 'Suecia', 'Europa', 'Estocolmo'),
    C(156, 'Suiza', 'Europa', 'Berna'),
    C(146, 'Surinam', 'América del Sur', 'Paramaribo'),
    C(166, 'Swazilandia', 'África', 'Mbabane'),
    C(22, 'Siria', 'Medio Oriente', 'Damasco'),
    C(120, 'Tayikistán', 'Asia', 'Dushanbe'),
    C(32, 'Taiwán', 'Asia', 'Taipei'),
    C(142, 'Tanzania', 'África', 'Dodoma'),
    C(108, 'Chad', 'África', 'NʻDjaména'),
    C(66, 'República Checa', 'Europa', 'Praga'),
    C(11, 'Tailandia', 'Asia', 'Bangkok'),
    C(171, 'Timor Oriental', 'Asia', 'Dili'),
    C(95, 'Togo', 'África', 'Lomé'),
    C(185, 'Tonga', 'Oceanía', 'Nukuʻalofa'),
    C(173, 'Trinidad y Tobago', 'Oceanía', 'Puerto España'),
    C(106, 'Túnez', 'África', 'Túnez'),
    C(107, 'Turkmenistán', 'Asia', 'Ashgabat'),
    C(17, 'Turquía', 'Medio Oriente', 'Ankara'),
    C(195, 'Tuvalu', 'Oceanía', 'Funafuti'),
    C(31, 'Ucrania', 'Europa', 'Kiev'),
    C(63, 'Uruguay', 'América del Sur', 'Montevideo'),
    C(176, 'Vanuatu', 'Oceanía', 'Port Vila'),
    C(198, 'Vaticano', 'Europa', 'Vaticano'),
    C(44, 'Venezuela', 'América del Sur', 'Caracas'),
    C(23, 'Vietnam', 'Asia', 'Hanoi'),
    C(60, 'Yemen', 'Medio Oriente', 'Sanaa'),
    C(64, 'Zambia', 'África', 'Lusaka'),
    C(58, 'Zimbabwe', 'África', 'Harare'),
  ];

  final List<C> dataIt = [
    C(26, "Afghanistan", "Medio Oriente", "Kabul"),
    C(36, 'Sud Africa', 'Africa', 'Pretoria'),
    C(105, 'Albania', 'Europa', 'Tirana'),
    C(20, 'Algeria', 'Africa', 'Algeri'),
    C(21, "Germania", "Europa", "Berlino"),
    C(183, "Andorra", "Europa", "Andorra la Vella"),
    C(35, 'Angola', 'Africa', 'Luanda'),
    C(184, 'Antigua e Barbuda', 'Oceania', 'Saint Johns'),
    C(19, "Arabia Saudita", "Medio Oriente", "Riyadh"),
    C(29, "Argentina", "Sud America", "Buenos Aires"),
    C(76, "Armenia", "Medio Oriente", "Yerevan"),
    C(138, "Australia", "Oceania", "Canberra"),
    C(46, 'Austria', 'Europa', 'Vienna'),
    C(39, 'Azerbaigian', 'Medio Oriente', 'Baku'),
    C(149, 'Bahamas', 'Oceania', 'Nassau'),
    C(155, 'Bahrain', 'Medio Oriente', 'Manama'),
    C(7, "Bangladesh", "Asia", "Dhaka"),
    C(161, "Barbados", "Oceania", "Bridgetown"),
    C(74, "Belgio", "Europa", "Bruxelles"),
    C(186, 'Belize', 'America Centrale', 'Belmopan'),
    C(151, 'Benin', 'Africa', 'Porto-Novo'),
    C(163, 'Bhutan', 'Asia', 'Thimphu'),
    C(50, "Bielorussia", "Europa", "Minsk"),
    C(87, "Birmania (Myanmar)", "Asia", "Naypyidaw"),
    C(92, 'Bolivia', 'Sud America', 'La Paz'),
    C(135, 'Bosnia ed Erzegovina', 'Europa', 'Sarajevo'),
    C(150, "Botswana", "Africa", "Gaborone"),
    C(33, "Brasile", "Sud America", "Brasilia"),
    C(181, "Brunei", "Asia", "Bandar Seri Begawan"),
    C(134, 'Bulgaria', 'Europa', 'Sofia'),
    C(81, "Burkina Faso", "Africa", "Ouagadougou"),
    C(73, 'Burundi', 'Africa', 'Gitega'),
    C(42, "Cambogia", "Asia", "Phnom Penh"),
    C(54, 'Camerun', 'Africa', 'Yaoundé'),
    C(91, "Canada", "Nord America", "Ottawa"),
    C(158, 'Capo Verde', 'Oceania', 'Praia'),
    C(110, "Repubblica Centrafricana", "Africa", "Bangui"),
    C(18, "Cile", "Sud America", "Santiago"),
    C(1, "Cina", "Asia", "Pechino"),
    C(144, "Cipro", "Medio Oriente", "Nicosia"),
    C(13, "Colombia", "Sud America", "Bogotà"),
    C(169, 'Comore', 'Oceania', 'Moroni'),
    C(75, 'Congo', 'Africa', 'Brazzaville'),
    C(3, "Repubblica Democratica del Congo", "Africa", "Kinshasa"),
    C(192, "Isole Cook", "Oceania", "Avarua"),
    C(25, "Corea del Nord", "Asia", "Pyongyang"),
    C(5, "Corea del Sud", "Asia", "Seoul"),
    C(139, "Costa Rica", "America Centrale", "San José"),
    C(130, 'Côte dʻIvoire', 'Africa', 'Yamoussoukro'),
    C(99, 'Croazia', 'Europa', 'Zagabria'),
    C(41, "Cuba", "Oceania", "L'Avana"),
    C(128, "Danimarca", "Europa", "Copenaghen"),
    C(129, 'Gibuti', 'Africa', 'Gibuti'),
    C(71, "Repubblica Dominicana", "Oceania", "Santo Domingo"),
    C(187, "Dominica", "Oceania", "Roseau"),
    C(14, 'Egitto', 'Medio Oriente', 'Il Cairo'),
    C(119, "Emirati Arabi Uniti", "Medio Oriente", "Abu Dhabi"),
    C(57, "Ecuador", "Sud America", "Quito"),
    C(123, 'Eritrea', 'Africa', 'Asmara'),
    C(24, 'Spagna', 'Europa', 'Madrid'),
    C(133, "Estonia", "Europa", "Tallinn"),
    C(116, "Stati Uniti", "Nord America", "Washington"),
    C(28, 'Etiopia', 'Africa', 'Addis Abeba'),
    C(165, 'Figi', 'Oceania', 'Suva'),
    C(118, 'Finlandia', 'Europa', 'Helsinki'),
    C(37, 'Francia', 'Europa', 'Parigi'),
    C(122, 'Gabon', 'Africa', 'Libreville'),
    C(178, "Gambia", "Africa", "Banjul"),
    C(79, "Georgia", "Medio Oriente", "Tbilisi"),
    C(53, "Ghana", "Africa", "Accra"),
    C(111, 'Grecia', 'Europa', 'Atene'),
    C(190, 'Grenada', 'Oceania', 'Saint-Georges'),
    C(84, "Guatemala", "America Centrale", "Guatemala"),
    C(61, 'Guinea', 'Africa', 'Conakry'),
    C(131, 'Guinea-Bissau', 'Africa', 'Bissau'),
    C(164, 'Guinea Equatoriale', 'Africa', 'Malabo'),
    C(157, "Guyana", "Sud America", "Georgetown"),
    C(67, 'Haiti', 'Oceania', 'Port-au-Prince'),
    C(109, 'Honduras', 'America Centrale', 'Tegucigalpa'),
    C(48, 'Ungheria', 'Europa', 'Budapest'),
    C(148, "India", "Asia", "Nuova Delhi"),
    C(6, "Indonesia", "Asia", "Giacarta"),
    C(15, "Iraq", "Medio Oriente", "Baghdad"),
    C(12, "Iran", "Medio Oriente", "Teheran"),
    C(82, 'Irlanda', 'Europa', 'Dublino'),
    C(160, "Islanda", "Europa", "Reykjavík"),
    C(90, "Israele", "Medio Oriente", "Gerusalemme"),
    C(30, 'Italia', 'Europa', 'Roma'),
    C(115, "Giamaica", "Oceania", "Kingston"),
    C(2, "Giappone", "Asia", "Tokyo"),
    C(34, "Giordania", "Medio Oriente", "Amman"),
    C(94, "Kazakistan", "Asia", "Noursoultan"),
    C(27, 'Kenya', 'Africa', 'Nairobi'),
    C(93, "Kirghizistan", "Asia", "Bishkek"),
    C(179, "Kiribati", "Oceania", "Tarawa"),
    C(152, "Kosovo", "Europa", "Pristina"),
    C(69, "Kuwait", "Medio Oriente", "Kuwait"),
    C(141, 'Laos', 'Asia', 'Vientiane'),
    C(143, 'Lesotho', 'Africa', 'Maseru'),
    C(114, "Lettonia", "Europa", "Riga"),
    C(56, "Libano", "Medio Oriente", "Beirut"),
    C(83, 'Liberia', 'Africa', 'Monrovia'),
    C(68, 'Libia', 'Africa', 'Tripoli'),
    C(193, 'Liechtenstein', 'Europa', 'Vaduz'),
    C(121, "Lituania", "Europa", "Vilnius"),
    C(167, 'Lussemburgo', 'Europa', 'Lussemburgo'),
    C(127, "Macedonia", "Europa", "Skopje"),
    C(55, 'Madagascar', 'Africa', 'Antananarivo'),
    C(62, 'Malaysia', 'Asia', 'Kuala Lumpur'),
    C(89, 'Malawi', 'Africa', 'Lilongwe'),
    C(162, 'Maldive', 'Oceania', 'Malé'),
    C(65, 'Mali', 'Africa', 'Bamako'),
    C(45, 'Marocco', 'Africa', 'Rabat'),
    C(182, "Isole Marshall", "Oceania", "Delap-Uliga-Darrit"),
    C(154, "Maurizio", "Oceania", "Port-Louis"),
    C(112, "Mauritania", "Africa", "Nouakchott"),
    C(8, "Messico", "Nord America", "Messico"),
    C(189, 'Micronesia', 'Oceania', 'Palikir'),
    C(102, 'Moldavia', 'Europa', 'Chișinău'),
    C(177, 'Monaco', 'Europa', 'Monte-Carlo'),
    C(88, "Mongolia", "Asia", "Ulan Bator"),
    C(153, 'Montenegro', 'Europa', 'Podgorica'),
    C(77, 'Mozambico', 'Africa', 'Maputo'),
    C(147, 'Namibia', 'Africa', 'Windhoek'),
    C(197, "Nauru", "Oceania", "Yaren"),
    C(97, "Nepal", "Asia", "Kathmandu"),
    C(86, "Nicaragua", "America Centrale", "Managua"),
    C(101, 'Niger', 'Africa', 'Niamey'),
    C(104, 'Nigeria', 'Africa', 'Abuja'),
    C(117, 'Norvegia', 'Europa', 'Oslo'),
    C(136, "Nuova Zelanda", "Oceania", "Wellington"),
    C(100, "Oman", "Medio Oriente", "Muscat"),
    C(52, 'Uganda', 'Africa', 'Kampala'),
    C(38, "Uzbekistan", "Asia", "Tashkent"),
    C(85, "Pakistan", "Asia", "Islamabad"),
    C(200, 'Palau', 'Oceania', 'Melekeok'),
    C(96, "Panama", "America Centrale", "Panama"),
    C(140, "Papua Nuova Guinea", "Oceania", "Port Moresby"),
    C(126, 'Paraguay', 'Sud America', 'Asunción'),
    C(98, 'Paesi Bassi', 'Europa', 'Amsterdam'),
    C(10, "Perù", "Sud America", "Lima"),
    C(51, "Filippine", "Asia", "Manila"),
    C(49, "Polonia", "Europa", "Varsavia"),
    C(124, 'Portogallo', 'Europa', 'Lisbona'),
    C(59, "Qatar", "Medio Oriente", "Doha"),
    C(43, 'Romania', 'Europa', 'Bucarest'),
    C(9, "Regno Unito", "Europa", "Londra"),
    C(4, "Russia", "Europa", "Mosca"),
    C(113, 'Ruanda', 'Africa', 'Kigali'),
    C(188, "Saint Kitts e Nevis", "Oceania", "Basseterre"),
    C(194, 'San Marino', 'Europa', 'San Marino'),
    C(174, "Saint Vincent e Grenadine", "Oceania", "Kingstown"),
    C(168, 'Santa Lucia', 'Oceania', 'Castries'),
    C(170, 'Solomon', 'Oceania', 'Honiara'),
    C(125, 'El Salvador', 'America Centrale', 'San Salvador'),
    C(175, 'Samoa', 'Oceania', 'Apia'),
    C(172, 'São Tomé e Príncipe', 'Oceania', 'São Tome'),
    C(80, "Senegal", "Africa", "Dakar"),
    C(70, 'Serbia', 'Europa', 'Belgrado'),
    C(180, "Seychelles", "Oceania", "Victoria"),
    C(78, 'Sierra Leone', 'Africa', 'Freetown'),
    C(16, "Singapore", "Asia", "Singapore"),
    C(132, 'Slovacchia', 'Europa', 'Bratislava'),
    C(145, 'Slovenia', 'Europa', 'Lubiana'),
    C(72, 'Somalia', 'Africa', 'Mogadiscio'),
    C(47, 'Sudan', 'Africa', 'Khartoum'),
    C(137, 'Sud Sudan', 'Africa', 'Djouba'),
    C(159, "Sri Lanka", "Asia", "Sri Jayawardenapura Kotte"),
    C(40, "Svezia", "Europa", "Stoccolma"),
    C(156, "Svizzera", "Europa", "Berna"),
    C(146, "Suriname", "Sud America", "Paramaribo"),
    C(166, 'Swaziland', 'Africa', 'Mbabane'),
    C(22, 'Siria', 'Medio Oriente', 'Damasco'),
    C(120, "Tagikistan", "Asia", "Dushanbe"),
    C(32, "Taiwan", "Asia", "Taipei"),
    C(142, "Tanzania", "Africa", "Dodoma"),
    C(108, "Ciad", "Africa", "NʻDjaména"),
    C(66, "Repubblica Ceca", "Europa", "Praga"),
    C(11, "Thailandia", "Asia", "Bangkok"),
    C(171, 'Timor Est', 'Asia', 'Dili'),
    C(95, 'Togo', 'Africa', 'Lomé'),
    C(185, 'Tonga', 'Oceania', 'Nukuʻalofa'),
    C(173, 'Trinidad e Tobago', 'Oceania', 'Port of Spain'),
    C(106, 'Tunisia', 'Africa', 'Tunisi'),
    C(107, 'Turkmenistan', 'Asia', 'Ashgabat'),
    C(17, "Turchia", "Medio Oriente", "Ankara"),
    C(195, 'Tuvalu', 'Oceania', 'Funafuti'),
    C(31, "Ucraina", "Europa", "Kiev"),
    C(63, 'Uruguay', 'Sud America', 'Montevideo'),
    C(176, 'Vanuatu', 'Oceania', 'Port Vila'),
    C(198, 'Vaticano', 'Europa', 'Vaticano'),
    C(44, 'Venezuela', 'Sud America', 'Caracas'),
    C(23, "Vietnam", "Asia", "Hanoi"),
    C(60, "Yemen", "Medio Oriente", "Sanaa"),
    C(64, 'Zambia', 'Africa', 'Lusaka'),
    C(58, 'Zimbabwe', 'Africa', 'Harare'),
  ];

  final List<C> dataPt = [
    C(26, 'Afeganistão', 'Oriente Médio', 'Cabul'),
    C(36, 'África do Sul', 'África', 'Pretória'),
    C(105, 'Albânia', 'Europa', 'Tirana'),
    C(20, 'Argélia', 'África', 'Argel'),
    C(21, 'Alemanha', 'Europa', 'Berlim'),
    C(183, 'Andorra', 'Europa', 'Andorra la Vella'),
    C(35, 'Angola', 'África', 'Luanda'),
    C(184, 'Antígua e Barbuda', 'Oceania', 'Saint Johns'),
    C(19, 'Arábia Saudita', 'Oriente Médio', 'Riade'),
    C(29, 'Argentina', 'América do Sul', 'Buenos Aires'),
    C(76, 'Armênia', 'Oriente Médio', 'Yerevan'),
    C(138, 'Austrália', 'Oceania', 'Canberra'),
    C(46, 'Áustria', 'Europa', 'Viena'),
    C(39, 'Azerbaijão', 'Oriente Médio', 'Baku'),
    C(149, 'Bahamas', 'Oceania', 'Nassau'),
    C(155, 'Bahrain', 'Oriente Médio', 'Manama'),
    C(7, 'Bangladesh', 'Ásia', 'Daca'),
    C(161, 'Barbados', 'Oceania', 'Bridgetown'),
    C(74, 'Bélgica', 'Europa', 'Bruxelas'),
    C(186, 'Belize', 'América Central', 'Belmopan'),
    C(151, 'Benin', 'África', 'Porto-Novo'),
    C(163, 'Butão', 'Ásia', 'Thimphu'),
    C(50, 'Bielo-Rússia', 'Europa', 'Minsk'),
    C(87, 'Burma (Myanmar)', 'África', 'Naypyidaw'),
    C(92, 'Bolívia', 'América do Sul', 'La Paz'),
    C(135, 'Bósnia e Herzegovina', 'Europa', 'Sarajevo'),
    C(150, 'Botswana', 'África', 'Gaborone'),
    C(33, 'Brasil', 'América do Sul', 'Brasília'),
    C(181, 'Brunei', 'Ásia', 'Bandar Seri Begawan'),
    C(134, 'Bulgária', 'Europa', 'Sofia'),
    C(81, 'Burkina Faso', 'África', 'Ouagadougou'),
    C(73, 'Burundi', 'África', 'Gitega'),
    C(42, 'Camboja', 'Ásia', 'Phnom Penh'),
    C(54, 'Camarões', 'África', 'Yaoundé'),
    C(91, 'Canadá', 'América do Norte', 'Ottawa'),
    C(158, 'Cabo Verde', 'Oceania', 'Praia'),
    C(110, 'República Centro-Africana', 'África', 'Bangui'),
    C(18, 'Chile', 'América do Sul', 'Santiago'),
    C(1, 'China', 'Ásia', 'Pequim'),
    C(144, 'Chipre', 'Oriente Médio', 'Nicósia'),
    C(13, 'Colômbia', 'América do Sul', 'Bogotá'),
    C(169, 'Comores', 'Oceania', 'Moroni'),
    C(75, 'Congo', 'África', 'Brazzaville'),
    C(3, 'República Democrática do Congo', 'África', 'Kinshasa'),
    C(192, 'Ilhas Cook', 'Oceania', 'Avarua'),
    C(25, 'Coreia do Norte', 'Ásia', 'Pyongyang'),
    C(5, 'Coreia do Sul', 'Ásia', 'Seul'),
    C(139, 'Costa Rica', 'América Central', 'San José'),
    C(130, 'Côte dʻIvoire', 'África', 'Yamoussoukro'),
    C(99, 'Croácia', 'Europa', 'Zagreb'),
    C(41, 'Cuba', 'Oceania', 'Havana'),
    C(128, 'Dinamarca', 'Europa', 'Copenhague'),
    C(129, 'Djibouti', 'África', 'Djibouti'),
    C(71, 'República Dominicana', 'Oceania', 'Santo Domingo'),
    C(187, 'Dominica', 'Oceania', 'Roseau'),
    C(14, 'Egito', 'Oriente Médio', 'Cairo'),
    C(119, 'Emirados Árabes Unidos', 'Oriente Médio', 'Abu Dhabi'),
    C(57, 'Equador', 'América do Sul', 'Quito'),
    C(123, 'Eritreia', 'África', 'Asmara'),
    C(24, 'Espanha', 'Europa', 'Madrid'),
    C(133, 'Estônia', 'Europa', 'Tallinn'),
    C(116, 'Estados Unidos', 'América do Norte', 'Washington'),
    C(28, 'Etiópia', 'África', 'Adis Abeba'),
    C(165, 'Fiji', 'Oceania', 'Suva'),
    C(118, 'Finlândia', 'Europa', 'Helsinque'),
    C(37, 'França', 'Europa', 'Paris'),
    C(122, 'Gabão', 'África', 'Libreville'),
    C(178, 'Gâmbia', 'África', 'Banjul'),
    C(79, 'Geórgia', 'Oriente Médio', 'Tbilisi'),
    C(53, 'Gana', 'África', 'Acra'),
    C(111, 'Grécia', 'Europa', 'Atenas'),
    C(190, 'Grenada', 'Oceania', 'Saint-Georges'),
    C(84, 'Guatemala', 'América Central', 'Guatemala'),
    C(61, 'Guiné', 'África', 'Conacri'),
    C(131, 'Guiné-Bissau', 'África', 'Bissau'),
    C(164, 'Guiné Equatorial', 'África', 'Malabo'),
    C(157, 'Guiana', 'América do Sul', 'Georgetown'),
    C(67, 'Haiti', 'Oceania', 'Port-au-Prince'),
    C(109, 'Honduras', 'América Central', 'Tegucigalpa'),
    C(48, 'Hungria', 'Europa', 'Budapeste'),
    C(148, 'Índia', 'Ásia', 'Nova Delhi'),
    C(6, 'Indonésia', 'Ásia', 'Jacarta'),
    C(15, 'Iraque', 'Oriente Médio', 'Bagdá'),
    C(12, 'Irã', 'Oriente Médio', 'Teerã'),
    C(82, 'Irlanda', 'Europa', 'Dublin'),
    C(160, 'Islândia', 'Europa', 'Reykjavík'),
    C(90, 'Israel', 'Oriente Médio', 'Jerusalém'),
    C(30, 'Itália', 'Europa', 'Roma'),
    C(115, 'Jamaica', 'Oceania', 'Kingston'),
    C(2, 'Japão', 'Ásia', 'Tóquio'),
    C(34, 'Jordânia', 'Oriente Médio', 'Amã'),
    C(94, 'Cazaquistão', 'Ásia', 'Noursoultan'),
    C(27, 'Quênia', 'África', 'Nairóbi'),
    C(93, 'Quirguistão', 'Ásia', 'Bishkek'),
    C(179, 'Kiribati', 'Oceania', 'Tarawa'),
    C(152, 'Kosovo', 'Europa', 'Pristina'),
    C(69, 'Kuwait', 'Oriente Médio', 'Kuwait'),
    C(141, 'Laos', 'Ásia', 'Vientiane'),
    C(143, 'Lesoto', 'África', 'Maseru'),
    C(114, 'Letônia', 'Europa', 'Riga'),
    C(56, 'Líbano', 'Oriente Médio', 'Beirute'),
    C(83, 'Libéria', 'África', 'Monróvia'),
    C(68, 'Líbia', 'África', 'Trípoli'),
    C(193, 'Liechtenstein', 'Europa', 'Vaduz'),
    C(121, 'Lituânia', 'Europa', 'Vilnius'),
    C(167, 'Luxemburgo', 'Europa', 'Luxemburgo'),
    C(127, 'Macedônia', 'Europa', 'Skopje'),
    C(55, 'Madagascar', 'África', 'Antananarivo'),
    C(62, 'Malásia', 'Ásia', 'Kuala Lumpur'),
    C(89, 'Malawi', 'África', 'Lilongwe'),
    C(162, 'Maldivas', 'Oceania', 'Malé'),
    C(65, 'Mali', 'África', 'Bamako'),
    C(45, 'Marrocos', 'África', 'Rabat'),
    C(182, 'Ilhas Marshall', 'Oceania', 'Delap-Uliga-Darrit'),
    C(154, 'Maurício', 'Oceania', 'Port-Louis'),
    C(112, 'Mauritânia', 'África', 'Nouakchott'),
    C(8, 'México', 'América do Norte', 'México'),
    C(189, 'Micronésia', 'Oceania', 'Palikir'),
    C(102, 'Moldávia', 'Europa', 'Chișinău'),
    C(177, 'Mônaco', 'Europa', 'Monte-Carlo'),
    C(88, 'Mongólia', 'Ásia', 'Ulan Bator'),
    C(153, 'Montenegro', 'Europa', 'Podgorica'),
    C(77, 'Moçambique', 'África', 'Maputo'),
    C(147, 'Namíbia', 'África', 'Windhoek'),
    C(197, 'Nauru', 'Oceania', 'Yaren'),
    C(97, 'Nepal', 'Ásia', 'Catmandu'),
    C(86, 'Nicarágua', 'América Central', 'Manágua'),
    C(101, 'Níger', 'África', 'Niamey'),
    C(104, 'Nigéria', 'África', 'Abuja'),
    C(117, 'Noruega', 'Europa', 'Oslo'),
    C(136, 'Nova Zelândia', 'Oceania', 'Wellington'),
    C(100, 'Omã', 'Oriente Médio', 'Muscat'),
    C(52, 'Uganda', 'África', 'Kampala'),
    C(38, 'Uzbequistão', 'Ásia', 'Tashkent'),
    C(85, 'Paquistão', 'Ásia', 'Islamabad'),
    C(200, 'Palau', 'Oceania', 'Melekeok'),
    C(96, 'Panamá', 'América Central', 'Panamá'),
    C(140, 'Papua Nova Guiné', 'Oceania', 'Port Moresby'),
    C(126, 'Paraguai', 'América do Sul', 'Assunção'),
    C(98, 'Holanda', 'Europa', 'Amsterdã'),
    C(10, 'Peru', 'América do Sul', 'Lima'),
    C(51, 'Filipinas', 'Ásia', 'Manila'),
    C(49, 'Polônia', 'Europa', 'Varsóvia'),
    C(124, 'Portugal', 'Europa', 'Lisboa'),
    C(59, 'Qatar', 'Oriente Médio', 'Doha'),
    C(43, 'Romênia', 'Europa', 'Bucareste'),
    C(9, 'Reino Unido', 'Europa', 'Londres'),
    C(4, 'Rússia', 'Europa', 'Moscou'),
    C(113, 'Ruanda', 'África', 'Kigali'),
    C(188, 'São Cristóvão e Neves', 'Oceania', 'Basseterre'),
    C(194, 'San Marino', 'Europa', 'San Marino'),
    C(174, 'São Vicente e Granadinas', 'Oceania', 'Kingstown'),
    C(168, 'Santa Lúcia', 'Oceania', 'Castries'),
    C(170, 'Salomão', 'Oceania', 'Honiara'),
    C(125, 'El Salvador', 'América Central', 'San Salvador'),
    C(175, 'Samoa', 'Oceania', 'Apia'),
    C(172, 'São Tomé e Príncipe', 'Oceania', 'São Tomé'),
    C(80, 'Senegal', 'África', 'Dakar'),
    C(70, 'Sérvia', 'Europa', 'Belgrado'),
    C(180, 'Seychelles', 'Oceania', 'Victoria'),
    C(78, 'Serra Leoa', 'África', 'Freetown'),
    C(16, 'Singapura', 'Ásia', 'Singapura'),
    C(132, 'Eslováquia', 'Europa', 'Bratislava'),
    C(145, 'Eslovênia', 'Europa', 'Ljubljana'),
    C(72, 'Somália', 'África', 'Mogadíscio'),
    C(47, 'Sudão', 'África', 'Cartum'),
    C(137, 'Sudão do Sul', 'África', 'Djouba'),
    C(159, 'Sri Lanka', 'Ásia', 'Sri Jayawardenapura Kotte'),
    C(40, 'Suécia', 'Europa', 'Estocolmo'),
    C(156, 'Suíça', 'Europa', 'Berna'),
    C(146, 'Suriname', 'América do Sul', 'Paramaribo'),
    C(166, 'Suazilândia', 'África', 'Mbabane'),
    C(22, 'Síria', 'Oriente Médio', 'Damasco'),
    C(120, 'Tajiquistão', 'Ásia', 'Duchambe'),
    C(32, 'Taiwan', 'Ásia', 'Taipei'),
    C(142, 'Tanzânia', 'África', 'Dodoma'),
    C(108, 'Chade', 'África', 'NʻDjaména'),
    C(66, 'República Tcheca', 'Europa', 'Praga'),
    C(11, 'Tailândia', 'Ásia', 'Bangkok'),
    C(171, 'Timor Leste', 'Ásia', 'Díli'),
    C(95, 'Togo', 'África', 'Lomé'),
    C(185, 'Tonga', 'Oceania', 'Nukuʻalofa'),
    C(173, 'Trinidad e Tobago', 'Oceania', 'Port of Spain'),
    C(106, 'Tunísia', 'África', 'Tunis'),
    C(107, 'Turcomenistão', 'Ásia', 'Ashgabat'),
    C(17, 'Turquia', 'Oriente Médio', 'Ancara'),
    C(195, 'Tuvalu', 'Oceania', 'Funafuti'),
    C(31, 'Ucrânia', 'Europa', 'Kiev'),
    C(63, 'Uruguai', 'América do Sul', 'Montevidéu'),
    C(176, 'Vanuatu', 'Oceania', 'Port Vila'),
    C(198, 'Vaticano', 'Europa', 'Vaticano'),
    C(44, 'Venezuela', 'América do Sul', 'Caracas'),
    C(23, 'Vietnã', 'Ásia', 'Hanói'),
    C(60, 'Iêmen', 'Oriente Médio', 'Sanaa'),
    C(64, 'Zâmbia', 'África', 'Lusaka'),
    C(58, 'Zimbábue', 'África', 'Harare'),
  ];

  final List<C> dataRu = [
    C(26, 'Афганистан', 'Ближний Восток', 'Кабул'),
    C(36, 'Южно-Африканская Республика', 'Африка', 'Претория'),
    C(105, 'Албания', 'Европа', 'Тирана'),
    C(20, 'Алжир', 'Африка', 'Алжир'),
    C(21, 'Германия', 'Европа', 'Берлин'),
    C(183, 'Андорра', 'Европа', 'Андорра-ла-Велья'),
    C(35, 'Ангола', 'Африка', 'Луанда'),
    C(184, 'Антигуа и Барбуда', 'Океания', 'Сент-Джонс'),
    C(19, 'Саудовская Аравия', 'Ближний Восток', 'Эр-Рияд'),
    C(29, 'Аргентина', 'Южная Америка', 'Буэнос-Айрес'),
    C(76, 'Армения', 'Ближний Восток', 'Ереван'),
    C(138, 'Австралия', 'Океания', 'Канберра'),
    C(46, 'Австрия', 'Европа', 'Вена'),
    C(39, 'Азербайджан', 'Ближний Восток', 'Баку'),
    C(149, 'Багамские острова', 'Океания', 'Нассау'),
    C(155, 'Бахрейн', 'Ближний Восток', 'Манама'),
    C(7, 'Бангладеш', 'Азия', 'Дакка'),
    C(161, 'Барбадос', 'Океания', 'Бриджтаун'),
    C(74, 'Бельгия', 'Европа', 'Брюссель'),
    C(186, 'Белиз', 'Центральная Америка', 'Бельмопан'),
    C(151, 'Бенин', 'Африка', 'Порто-Ново'),
    C(163, 'Бутан', 'Азия', 'Тхимпху'),
    C(50, 'Беларусь', 'Европа', 'Минск'),
    C(87, 'Бирма (Мьянма)', 'Азия', 'Нейпьидо'),
    C(92, 'Боливия', 'Южная Америка', 'Ла-Пас'),
    C(135, 'Босния и Герцеговина', 'Европа', 'Сараево'),
    C(150, 'Ботсвана', 'Африка', 'Габороне'),
    C(33, 'Бразилия', 'Южная Америка', 'Бразилиа'),
    C(181, 'Бруней', 'Азия', 'Бандар-Сери-Бегаван'),
    C(134, 'Болгария', 'Европа', 'София'),
    C(81, 'Буркина-Фасо', 'Африка', 'Уагадугу'),
    C(73, 'Бурунди', 'Африка', 'Гитега'),
    C(42, 'Камбоджа', 'Азия', 'Пномпень'),
    C(54, 'Камерун', 'Африка', 'Яунде'),
    C(91, 'Канада', 'Северная Америка', 'Оттава'),
    C(158, 'Кабо-Верде', 'Океания', 'Прая'),
    C(110, 'Центральноафриканская Республика', 'Африка', 'Банги'),
    C(18, 'Чили', 'Южная Америка', 'Сантьяго'),
    C(1, 'Китай', 'Азия', 'Пекин'),
    C(144, 'Кипр', 'Ближний Восток', 'Никосия'),
    C(13, 'Колумбия', 'Южная Америка', 'Богота'),
    C(169, 'Коморские острова', 'Океания', 'Морони'),
    C(75, 'Конго', 'Африка', 'Браззавиль'),
    C(3, 'Демократическая Республика Конго', 'Африка', 'Киншаса'),
    C(192, 'Острова Кука', 'Океания', 'Аваруа'),
    C(25, 'Северная Корея', 'Азия', 'Пхеньян'),
    C(5, 'Южная Корея', 'Азия', 'Сеул'),
    C(139, 'Коста-Рика', 'Центральная Америка', 'Сан-Хосе'),
    C(130, 'Кот-д`Ивуар', 'Африка', 'Ямусукро'),
    C(99, 'Хорватия', 'Европа', 'Загреб'),
    C(41, 'Куба', 'Океания', 'Гавана'),
    C(128, 'Дания', 'Европа', 'Копенгаген'),
    C(129, 'Джибути', 'Африка', 'Джибути'),
    C(71, 'Доминиканская Республика', 'Океания', 'Санто-Доминго'),
    C(187, 'Доминика', 'Океания', 'Розо'),
    C(14, 'Египет', 'Ближний Восток', 'Каир'),
    C(119, 'Объединенные Арабские Эмираты', 'Ближний Восток', 'Абу-Даби'),
    C(57, 'Эквадор', 'Южная Америка', 'Кито'),
    C(123, 'Эритрея', 'Африка', 'Асмэра'),
    C(24, 'Испания', 'Европа', 'Мадрид'),
    C(133, 'Эстония', 'Европа', 'Таллинн'),
    C(116, 'США', 'Северная Америка', 'Вашингтон'),
    C(28, 'Эфиопия', 'Африка', 'Аддис-Абеба'),
    C(165, 'Фиджи', 'Океания', 'Сува'),
    C(118, 'Финляндия', 'Европа', 'Хельсинки'),
    C(37, 'Франция', 'Европа', 'Париж'),
    C(122, 'Габон', 'Африка', 'Либревиль'),
    C(178, 'Гамбия', 'Африка', 'Банжул'),
    C(79, 'Грузия', 'Ближний Восток', 'Тбилиси'),
    C(53, 'Гана', 'Африка', 'Аккра'),
    C(111, 'Греция', 'Европа', 'Афины'),
    C(190, 'Гренада', 'Океания', 'Сен-Жорж'),
    C(84, 'Гватемала', 'Центральная Америка', 'Гватемала'),
    C(61, 'Гвинея', 'Африка', 'Конакри'),
    C(131, 'Гвинея-Бисау', 'Африка', 'Бисау'),
    C(164, 'Экваториальная Гвинея', 'Африка', 'Малабо'),
    C(157, 'Гайана', 'Южная Америка', 'Джорджтаун'),
    C(67, 'Гаити', 'Океания', 'Порт-о-Пренс'),
    C(109, 'Гондурас', 'Центральная Америка', 'Тегусигальпа'),
    C(48, 'Венгрия', 'Европа', 'Будапешт'),
    C(148, 'Индия', 'Азия', 'Нью-Дели'),
    C(6, 'Индонезия', 'Азия', 'Джакарта'),
    C(15, 'Ирак', 'Ближний Восток', 'Багдад'),
    C(12, 'Иран', 'Ближний Восток', 'Тегеран'),
    C(82, 'Ирландия', 'Европа', 'Дублин'),
    C(160, 'Исландия', 'Европа', 'Рейкьявик'),
    C(90, 'Израиль', 'Ближний Восток', 'Иерусалим'),
    C(30, 'Италия', 'Европа', 'Рим'),
    C(115, 'Ямайка', 'Океания', 'Кингстон'),
    C(2, 'Япония', 'Азия', 'Токио'),
    C(34, 'Иордания', 'Ближний Восток', 'Амман'),
    C(94, 'Казахстан', 'Азия', 'Нурсултан'),
    C(27, 'Кения', 'Африка', 'Найроби'),
    C(93, 'Кыргызстан', 'Азия', 'Бишкек'),
    C(179, 'Кирибати', 'Океания', 'Тарава'),
    C(152, 'Косово', 'Европа', 'Приштина'),
    C(69, 'Кувейт', 'Ближний Восток', 'Кувейт'),
    C(141, 'Лаос', 'Азия', 'Вьентьян'),
    C(143, 'Лесото', 'Африка', 'Масеру'),
    C(114, 'Латвия', 'Европа', 'Рига'),
    C(56, 'Ливан', 'Ближний Восток', 'Бейрут'),
    C(83, 'Либерия', 'Африка', 'Монровия'),
    C(68, 'Ливия', 'Африка', 'Триполи'),
    C(193, 'Лихтенштейн', 'Европа', 'Вадуц'),
    C(121, 'Литва', 'Европа', 'Вильнюс'),
    C(167, 'Люксембург', 'Европа', 'Люксембург'),
    C(127, 'Македония', 'Европа', 'Скопье'),
    C(55, 'Мадагаскар', 'Африка', 'Антананариву'),
    C(62, 'Малайзия', 'Азия', 'Куала-Лумпур'),
    C(89, 'Малави', 'Африка', 'Лилонгве'),
    C(162, 'Мальдивы', 'Океания', 'Мале'),
    C(65, 'Мали', 'Африка', 'Бамако'),
    C(45, 'Марокко', 'Африка', 'Рабат'),
    C(182, 'Маршалловы острова', 'Океания', 'Делап-Улига-Даррит'),
    C(154, 'Маврикий', 'Океания', 'Порт-Луи'),
    C(112, 'Мавритания', 'Африка', 'Нуакшот'),
    C(8, 'Мексика', 'Северная Америка', 'Мексика'),
    C(189, 'Микронезия', 'Океания', 'Паликир'),
    C(102, 'Молдавия', 'Европа', 'Кишинев'),
    C(177, 'Монако', 'Европа', 'Монте-Карло'),
    C(88, 'Монголия', 'Азия', 'Улан-Батор'),
    C(153, 'Черногория', 'Европа', 'Подгорица'),
    C(77, 'Мозамбик', 'Африка', 'Мапуту'),
    C(147, 'Намибия', 'Африка', 'Виндхук'),
    C(197, 'Науру', 'Океания', 'Ярен'),
    C(97, 'Непал', 'Азия', 'Катманду'),
    C(86, 'Никарагуа', 'Центральная Америка', 'Манагуа'),
    C(101, 'Нигер', 'Африка', 'Ниамей'),
    C(104, 'Нигерия', 'Африка', 'Абуджа'),
    C(117, 'Норвегия', 'Европа', 'Осло'),
    C(136, 'Новая Зеландия', 'Океания', 'Веллингтон'),
    C(100, 'Оман', 'Ближний Восток', 'Маскат'),
    C(52, 'Уганда', 'Африка', 'Кампала'),
    C(38, 'Узбекистан', 'Азия', 'Ташкент'),
    C(85, 'Пакистан', 'Азия', 'Исламабад'),
    C(200, 'Палау', 'Океания', 'Мелекеок'),
    C(96, 'Панама', 'Центральная Америка', 'Панама'),
    C(140, 'Папуа-Новая Гвинея', 'Океания', 'Порт-Морсби'),
    C(126, 'Парагвай', 'Южная Америка', 'Асунсьон'),
    C(98, 'Нидерланды', 'Европа', 'Амстердам'),
    C(10, 'Перу', 'Южная Америка', 'Лима'),
    C(51, 'Филиппины', 'Азия', 'Манила'),
    C(49, 'Польша', 'Европа', 'Варшава'),
    C(124, 'Португалия', 'Европа', 'Лиссабон'),
    C(59, 'Катар', 'Ближний Восток', 'Доха'),
    C(43, 'Румыния', 'Европа', 'Бухарест'),
    C(9, 'Великобритания', 'Европа', 'Лондон'),
    C(4, 'Россия', 'Европа', 'Москва'),
    C(113, 'Руанда', 'Африка', 'Кигали'),
    C(188, 'Сент-Китс и Невис', 'Океания', 'Бастер'),
    C(194, 'Сан-Марино', 'Европа', 'Сан-Марино'),
    C(174, 'Сент-Винсент и Гренадины', 'Океания', 'Кингстаун'),
    C(168, 'Сент-Люсия', 'Океания', 'Кастри'),
    C(170, 'Соломон', 'Океания', 'Хониара'),
    C(125, 'Сальвадор', 'Центральная Америка', 'Сан-Сальвадор'),
    C(175, 'Самоа', 'Океания', 'Апиа'),
    C(172, 'Сан-Томе и Принсипи', 'Океания', 'Сан-Томе'),
    C(80, 'Сенегал', 'Африка', 'Дакар'),
    C(70, 'Сербия', 'Европа', 'Белград'),
    C(180, 'Сейшелыские острова', 'Океания', 'Виктория'),
    C(78, 'Сьерра-Леоне', 'Африка', 'Фритаун'),
    C(16, 'Сингапур', 'Азия', 'Сингапур'),
    C(132, 'Словакия', 'Европа', 'Братислава'),
    C(145, 'Словения', 'Европа', 'Любляна'),
    C(72, 'Сомали', 'Африка', 'Могадишо'),
    C(47, 'Судан', 'Африка', 'Хартум'),
    C(137, 'Южный Судан', 'Африка', 'Джуба'),
    C(159, 'Шри-Ланка', 'Азия', 'Шри-Джаяварденапура-Котте'),
    C(40, 'Швеция', 'Европа', 'Стокгольм'),
    C(156, 'Швейцария', 'Европа', 'Берн'),
    C(146, 'Суринам', 'Южная Америка', 'Парамарибо'),
    C(166, 'Свазиленд', 'Африка', 'Мбабане'),
    C(22, 'Сирия', 'Ближний Восток', 'Дамаск'),
    C(120, 'Таджикистан', 'Азия', 'Душанбе'),
    C(32, 'Тайвань', 'Азия', 'Тайбэй'),
    C(142, 'Танзания', 'Африка', 'Додома'),
    C(108, 'Чад', 'Африка', 'Нджамена'),
    C(66, 'Чехия', 'Европа', 'Прага'),
    C(11, 'Таиланд', 'Азия', 'Бангкок'),
    C(171, 'Восточный Тимор', 'Азия', 'Дили'),
    C(95, 'Того', 'Африка', 'Ломе'),
    C(185, 'Тонга', 'Океания', 'Нукуалофа'),
    C(173, 'Тринидад и Тобаго', 'Океания', 'Порт-оф-Спейн'),
    C(106, 'Тунис', 'Африка', 'Тунис'),
    C(107, 'Туркменистан', 'Азия', 'Ашхабад'),
    C(17, 'Турция', 'Ближний Восток', 'Анкара'),
    C(195, 'Тувалу', 'Океания', 'Фунафути'),
    C(31, 'Украина', 'Европа', 'Киев'),
    C(63, 'Уругвай', 'Южная Америка', 'Монтевидео'),
    C(176, 'Вануату', 'Океания', 'Порт-Вила'),
    C(198, 'Ватикан', 'Европа', 'Ватикан'),
    C(44, 'Венесуэла', 'Южная Америка', 'Каракас'),
    C(23, 'Вьетнам', 'Азия', 'Ханой'),
    C(60, 'Йемен', 'Ближний Восток', 'Сана'),
    C(64, 'Замбия', 'Африка', 'Лусака'),
    C(58, 'Зимбабве', 'Африка', 'Хараре'),
  ];

  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  String language = 'fr';
  List<C> data;

  @override
  Widget build(BuildContext context) {
    if (language == 'fr') data = widget.dataFr;
    if (language == 'en') data = widget.dataEn;
    if (language == 'de') data = widget.dataDe;
    if (language == 'es') data = widget.dataEs;
    if (language == 'it') data = widget.dataIt;
    if (language == 'pt') data = widget.dataPt;
    if (language == 'ru') data = widget.dataRu;

    return Scaffold(
      backgroundColor: Colors.black,
      // appBar: AppBar(
      //   backgroundColor: Colors.black,
      //   title: Container(
      //     alignment: Alignment.center,
      //     child: AutoSizeText('© Shchegolev 2021, shchnad@gmail.com',
      //         style: TextStyle(
      //             color: Colors.white, fontSize: 20)),
      //   ),
      // ),
      body: SafeArea(
        child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
          Container(
            child: AutoSizeText(
              'GeographY',
              style: TextStyle(
                  color: Colors.white, fontSize: 50, fontFamily: 'RockSalt'),
            ),
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Container(
                width: (MediaQuery.of(context).size.width) / 2.21,
                height: MediaQuery.of(context).size.height / 9,
                decoration: BoxDecoration(color: Theme.of(context).accentColor),
                padding: EdgeInsets.all(8.0),
                child: Center(
                  child: FittedBox(
                    fit: BoxFit.fitWidth,
                    child: DropdownButton(
                        dropdownColor: Theme.of(context).accentColor,
                        style: TextStyle(
                          fontSize: 40,
                          color: Colors.black,
                          fontWeight: FontWeight.w700,
                          // backgroundColor: Theme.of(context).accentColor,
                        ),
                        value: language,
                        icon: Padding(
                          padding: const EdgeInsets.all(8.0),
                          // child: Container(
                          //   child: LayoutBuilder(builder: (context, constraint) {
                          //     return Icon(
                          //       Icons.language,
                          //       size: constraint.biggest.height,
                          //       color: Colors.black,
                          //     );
                          //   }),
                          // ),
                        ),
                        items: [
                          DropdownMenuItem(
                              child: AutoSizeText(
                                'Français',
                              ),
                              value: 'fr'),
                          DropdownMenuItem(
                              child: AutoSizeText('English'), value: 'en'),
                          DropdownMenuItem(
                              child: AutoSizeText('Deutsch'), value: 'de'),
                          DropdownMenuItem(
                              child: AutoSizeText('Español'), value: 'es'),
                          DropdownMenuItem(
                              child: AutoSizeText('Italiano'), value: 'it'),
                          DropdownMenuItem(
                              child: AutoSizeText('Português'), value: 'pt'),
                          DropdownMenuItem(
                              child: AutoSizeText('Русский'), value: 'ru'),
                        ],
                        onChanged: (value) {
                          setState(() {
                            language = value;
                          });
                        }),
                  ),
                ),
              ),
              SizedBox(
                width: 10,
              ),
              InkWell(
                onTap: () {
                  Navigator.push(
                      context,
                      MaterialPageRoute(
                          builder: (context) =>
                              Countries(data: data, language: language)));
                },
                child: Container(
                  width: (MediaQuery.of(context).size.width) / 2.21,
                  height: MediaQuery.of(context).size.height / 9,
                  decoration:
                      BoxDecoration(color: Theme.of(context).accentColor),
                  child: Padding(
                    padding: const EdgeInsets.all(10.0),
                    child: LayoutBuilder(builder: (context, constraint) {
                      return new Icon(
                        Icons.school,
                        size: constraint.biggest.height,
                        color: Colors.black,
                      );
                    }),
                  ),
                ),
              ),
            ],
          ),
          SizedBox(
            height: 10,
          ),
          Container(
            width: MediaQuery.of(context).size.width,
            height: MediaQuery.of(context).size.height / 2.73,
            decoration: BoxDecoration(
                image: DecorationImage(
                    image: AssetImage('assets/images/world.jpg'))),
          ),
          SizedBox(
            height: 10,
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              InkWell(
                onTap: () {
                  Navigator.push(
                      context,
                      MaterialPageRoute(
                          builder: (context) => Quizz(
                              data: data,
                              quizzType: 'capital',
                              language: language)));
                },
                child: Container(
                  width: (MediaQuery.of(context).size.width) / 2.21,
                  height: MediaQuery.of(context).size.height / 9,
                  decoration:
                      BoxDecoration(color: Theme.of(context).accentColor),
                  child: Padding(
                    padding: const EdgeInsets.all(10.0),
                    child: LayoutBuilder(builder: (context, constraint) {
                      return new Icon(
                        Icons.emoji_transportation,
                        size: constraint.biggest.height,
                        color: Colors.black,
                      );
                    }),
                  ),
                ),
              ),
              SizedBox(
                width: 10,
              ),
              InkWell(
                onTap: () {
                  Navigator.push(
                      context,
                      MaterialPageRoute(
                          builder: (context) => Quizz(
                              data: data,
                              quizzType: 'flag',
                              language: language)));
                },
                child: Container(
                  width: (MediaQuery.of(context).size.width) / 2.21,
                  height: MediaQuery.of(context).size.height / 9,
                  decoration:
                      BoxDecoration(color: Theme.of(context).accentColor),
                  child: Padding(
                    padding: const EdgeInsets.all(10.0),
                    child: LayoutBuilder(builder: (context, constraint) {
                      return new Icon(
                        Icons.emoji_flags,
                        size: constraint.biggest.height,
                        color: Colors.black,
                      );
                    }),
                  ),
                ),
              ),
            ],
          ),
        ]),
      ),
    );
  }
}
